//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCode
    {
        public EventCode()
        {
            this.EventTemplates = new HashSet<EventTemplate>();
        }
    
        public int EventCode1 { get; set; }
        public string EventAssociated { get; set; }
        public int EventGroupId { get; set; }
    
        public virtual EventGroup EventGroup { get; set; }
        public virtual ICollection<EventTemplate> EventTemplates { get; set; }
    }
}
