//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSMTPConfiguration
    {
        public int ID { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPPort { get; set; }
        public string SMTPUser { get; set; }
        public string SMTPPassword { get; set; }
        public Nullable<bool> UseAuthentication { get; set; }
        public Nullable<bool> UseSSL { get; set; }
        public string FromAddress { get; set; }
        public string EmailDisplayName { get; set; }
        public string Name { get; set; }
    }
}
