//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblweatherchcurrent
    {
        public int ID { get; set; }
        public string CityName { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public Nullable<System.DateTime> CurrentDateTime { get; set; }
        public string WeatherType { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string Observation_Time { get; set; }
        public string ObservationTime { get; set; }
        public string Local_Time { get; set; }
        public string LocalTime { get; set; }
        public string Weather { get; set; }
        public string currenttemp { get; set; }
        public string currenthumidity { get; set; }
        public string wind_string { get; set; }
        public string Winddirection { get; set; }
        public string windblow { get; set; }
        public string pressure { get; set; }
        public string dewpoint { get; set; }
        public string heatindex { get; set; }
        public string visibility { get; set; }
        public string Precipitation { get; set; }
        public string feelslike { get; set; }
        public string UV { get; set; }
        public string Icon { get; set; }
        public string Icon_url { get; set; }
        public int AlertID { get; set; }
    }
}
