//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.Group = new HashSet<Group>();
        }
    
        public int PermissionId { get; set; }
        public string PermissionName { get; set; }
    
        public virtual ICollection<Group> Group { get; set; }
    }
}
