//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInvoice
    {
        public int InvoiceId { get; set; }
        public Nullable<int> PriorityCode { get; set; }
        public int DeletionStateCode { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string InvoiceNumber { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalLineItemAmount { get; set; }
        public Nullable<decimal> TotalLineItemDiscountAmount { get; set; }
        public Nullable<decimal> TotalAmountLessFreight { get; set; }
        public Nullable<decimal> TotalDiscountAmount { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int StateCode { get; set; }
        public string BillTo_Name { get; set; }
        public string BillTo_Line1 { get; set; }
        public string BillTo_Line2 { get; set; }
        public string BillTo_Line3 { get; set; }
        public string BillTo_City { get; set; }
        public string BillTo_StateOrProvince { get; set; }
        public string BillTo_Country { get; set; }
        public string BillTo_PostalCode { get; set; }
        public string BillTo_Telephone { get; set; }
        public string BillTo_Fax { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> TimeZoneId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
