//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmPanel : Interface
    {
        public Nullable<int> EventTypeTemplateId { get; set; }
        public Nullable<int> AlarmPanelTypeId { get; set; }
        public string InterfaceDeviceIP { get; set; }
        public string InterfaceDevicePort { get; set; }
    
        public virtual EventTypeTemplate EventTypeTemplate { get; set; }
    }
}
