//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertTemplateCondition
    {
        public int AlertTemplateConditionId { get; set; }
        public int AlertTemplateId { get; set; }
        public string EventFieldName { get; set; }
        public string EventFieldType { get; set; }
        public int ComparationOperationId { get; set; }
        public string Value { get; set; }
    
        public virtual AlertTemplate AlertTemplate { get; set; }
        public virtual ComparisonOperation ComparisonOperation { get; set; }
    }
}
