//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceVAnalyticsSchedule
    {
        public int DevSchID { get; set; }
        public long DeviceID { get; set; }
        public bool DevSchEnb { get; set; }
        public int nDay { get; set; }
        public int nHrs { get; set; }
    }
}
