//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventFieldDefinition
    {
        public EventFieldDefinition()
        {
            this.DeviceExternalIdDefinition = new HashSet<DeviceExternalIdDefinition>();
        }
    
        public int EventFieldId { get; set; }
        public string FieldName { get; set; }
        public int StartByte { get; set; }
        public int NumberOfBytes { get; set; }
    
        public virtual EventTypeTemplate EventTypeTemplate { get; set; }
        public virtual EventFieldType EventFieldType { get; set; }
        public virtual ICollection<DeviceExternalIdDefinition> DeviceExternalIdDefinition { get; set; }
    }
}
