//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentReportResource
    {
        public long IncidentReportResourceId { get; set; }
        public long IncidentReportId { get; set; }
        public System.Guid ResourceId { get; set; }
        public System.DateTime Appended { get; set; }
    
        public virtual IncidentReport IncidentReport { get; set; }
        public virtual ResourcesData ResourcesData { get; set; }
    }
}
