//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interface
    {
        public Interface()
        {
            this.Devices = new HashSet<Device>();
            this.DeviceExternalIdDefinition = new HashSet<DeviceExternalIdDefinition>();
            this.NVR = new HashSet<NVR>();
        }
    
        public int InterfaceId { get; set; }
        public int AccountId { get; set; }
        public int InterfaceTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual InterfaceType InterfaceType { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
        public virtual Site Site { get; set; }
        public virtual ICollection<DeviceExternalIdDefinition> DeviceExternalIdDefinition { get; set; }
        public virtual ICollection<NVR> NVR { get; set; }
    }
}
