//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvrAlertType
    {
        public NvrAlertType()
        {
            this.AccountNvrAlertType = new HashSet<AccountNvrAlertType>();
        }
    
        public int NvrAlertTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AccountNvrAlertType> AccountNvrAlertType { get; set; }
    }
}
