//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Address = new HashSet<Address>();
            this.Contact = new HashSet<Contact>();
            this.User = new HashSet<User>();
            this.PersonContactType = new HashSet<PersonContactType>();
        }
    
        public int PersonId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string NickName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> AgeRange { get; set; }
        public Nullable<int> Ethnicity { get; set; }
        public string Description { get; set; }
        public Nullable<int> GenderCode { get; set; }
        public Nullable<int> EducationCode { get; set; }
        public string ExternalIdentifier { get; set; }
        public byte[] Portrait { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string JobTitle { get; set; }
        public string Password { get; set; }
        public string PrimaryAccountAdministratorPassword { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual Account Account { get; set; }
        public virtual ICollection<PersonContactType> PersonContactType { get; set; }
    }
}
