//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatrixEvtInfo
    {
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<int> EVTSeqNo { get; set; }
        public string EvtDataStr { get; set; }
        public Nullable<System.DateTime> IDateTime { get; set; }
        public Nullable<int> ProcFlag { get; set; }
    }
}
