//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLocation
    {
        public int LocationId { get; set; }
        public string Username { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public decimal Alt { get; set; }
        public bool IsFavorite { get; set; }
        public Nullable<double> Zoomlevel { get; set; }
        public string Favaddress { get; set; }
    }
}
