//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using Rhino.Security;
    using System;
    using System.Collections.Generic;

    public partial class User : IUser
    {
        public User()
        {
            //this.Group = new HashSet<Group>();
        }

        public virtual int UserId { get; set; }
        public virtual string UserSid { get; set; }
        public virtual Nullable<int> UserTypeId { get; set; }
        public virtual int PersonId { get; set; }
        public virtual int StatusCode { get; set; }
        public virtual Nullable<System.Guid> MembershipUserId { get; set; }
        public virtual Person Person { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<UsersGroup> UsersGroups { get; set; }
        public virtual MUser MembershipUser { get; set; }
        private object lockKey = new object();

        private SecurityInfo _securityInfo;
        public virtual SecurityInfo SecurityInfo
        {
            get
            {
                if (_securityInfo == null)
                {
                    lock (lockKey)
                    {
                        if (_securityInfo == null)
                        {
                            _securityInfo = new SecurityInfo(MembershipUser.UserName, UserId);
                        }
                    }
                }

                return _securityInfo;
            }
        }
    }
}
