//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuesHistory
    {
        public long ValuesHistoryId { get; set; }
        public string ItemId { get; set; }
        public Nullable<double> Value { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
