//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.AutherizationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneLocation
    {
        public long LocationId { get; set; }
        public long ZoneId { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
    
        public virtual Zone Zone { get; set; }
    }
}
