//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.AlertsCreationServiceRef {
    using System.Runtime.Serialization;
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlertsCreationServiceRef.IAlertsCreationService")]
    public interface IAlertsCreationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/SubmitNewAlert", ReplyAction="http://tempuri.org/IAlertsCreationService/SubmitNewAlertResponse")]
        bool SubmitNewAlert(string alert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/SubmitNewAlert", ReplyAction="http://tempuri.org/IAlertsCreationService/SubmitNewAlertResponse")]
        System.Threading.Tasks.Task<bool> SubmitNewAlertAsync(string alert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/SubmitNewAlertDto", ReplyAction="http://tempuri.org/IAlertsCreationService/SubmitNewAlertDtoResponse")]
        bool SubmitNewAlertDto(AMS.Broker.Contracts.DTO.Alert alert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/SubmitNewAlertDto", ReplyAction="http://tempuri.org/IAlertsCreationService/SubmitNewAlertDtoResponse")]
        System.Threading.Tasks.Task<bool> SubmitNewAlertDtoAsync(AMS.Broker.Contracts.DTO.Alert alert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/SubmitNewAlertMycs", ReplyAction="http://tempuri.org/IAlertsCreationService/SubmitNewAlertMycsResponse")]
        long SubmitNewAlertMycs(AMS.Broker.Contracts.DTO.Alert alert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/SubmitNewAlertMycs", ReplyAction="http://tempuri.org/IAlertsCreationService/SubmitNewAlertMycsResponse")]
        System.Threading.Tasks.Task<long> SubmitNewAlertMycsAsync(AMS.Broker.Contracts.DTO.Alert alert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/SubmitNewAlertEdgeAnalytics", ReplyAction="http://tempuri.org/IAlertsCreationService/SubmitNewAlertEdgeAnalyticsResponse")]
        bool SubmitNewAlertEdgeAnalytics(AMS.Broker.Contracts.DTO.Alert alert, byte[] managedArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/SubmitNewAlertEdgeAnalytics", ReplyAction="http://tempuri.org/IAlertsCreationService/SubmitNewAlertEdgeAnalyticsResponse")]
        System.Threading.Tasks.Task<bool> SubmitNewAlertEdgeAnalyticsAsync(AMS.Broker.Contracts.DTO.Alert alert, byte[] managedArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/CreatePAAlert", ReplyAction="http://tempuri.org/IAlertsCreationService/CreatePAAlertResponse")]
        bool CreatePAAlert(string strData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlertsCreationService/CreatePAAlert", ReplyAction="http://tempuri.org/IAlertsCreationService/CreatePAAlertResponse")]
        System.Threading.Tasks.Task<bool> CreatePAAlertAsync(string strData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlertsCreationServiceChannel : AMS.Broker.IntegrationService.AlertsCreationServiceRef.IAlertsCreationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlertsCreationServiceClient : System.ServiceModel.ClientBase<AMS.Broker.IntegrationService.AlertsCreationServiceRef.IAlertsCreationService>, AMS.Broker.IntegrationService.AlertsCreationServiceRef.IAlertsCreationService {
        
        public AlertsCreationServiceClient() {
        }
        
        public AlertsCreationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlertsCreationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlertsCreationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlertsCreationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SubmitNewAlert(string alert) {
            return base.Channel.SubmitNewAlert(alert);
        }
        
        public System.Threading.Tasks.Task<bool> SubmitNewAlertAsync(string alert) {
            return base.Channel.SubmitNewAlertAsync(alert);
        }
        
        public bool SubmitNewAlertDto(AMS.Broker.Contracts.DTO.Alert alert) {
            return base.Channel.SubmitNewAlertDto(alert);
        }
        
        public System.Threading.Tasks.Task<bool> SubmitNewAlertDtoAsync(AMS.Broker.Contracts.DTO.Alert alert) {
            return base.Channel.SubmitNewAlertDtoAsync(alert);
        }
        
        public long SubmitNewAlertMycs(AMS.Broker.Contracts.DTO.Alert alert) {
            return base.Channel.SubmitNewAlertMycs(alert);
        }
        
        public System.Threading.Tasks.Task<long> SubmitNewAlertMycsAsync(AMS.Broker.Contracts.DTO.Alert alert) {
            return base.Channel.SubmitNewAlertMycsAsync(alert);
        }
        
        public bool SubmitNewAlertEdgeAnalytics(AMS.Broker.Contracts.DTO.Alert alert, byte[] managedArray) {
            return base.Channel.SubmitNewAlertEdgeAnalytics(alert, managedArray);
        }
        
        public System.Threading.Tasks.Task<bool> SubmitNewAlertEdgeAnalyticsAsync(AMS.Broker.Contracts.DTO.Alert alert, byte[] managedArray) {
            return base.Channel.SubmitNewAlertEdgeAnalyticsAsync(alert, managedArray);
        }
        
        public bool CreatePAAlert(string strData) {
            return base.Channel.CreatePAAlert(strData);
        }
        
        public System.Threading.Tasks.Task<bool> CreatePAAlertAsync(string strData) {
            return base.Channel.CreatePAAlertAsync(strData);
        }
    }
}
