//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertTemplate
    {
        public AlertTemplate()
        {
            this.AlertTemplateCondition = new HashSet<AlertTemplateCondition>();
            this.AlertTemplateValue = new HashSet<AlertTemplateValue>();
        }
    
        public int AlertTemplateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AlertTemplateCondition> AlertTemplateCondition { get; set; }
        public virtual ICollection<AlertTemplateValue> AlertTemplateValue { get; set; }
    }
}
