//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Event = new HashSet<Event>();
        }
    
        public int AreaId { get; set; }
        public int SiteId { get; set; }
        public long InfoId { get; set; }
        public string Description { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<double> Celing { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual Info Info { get; set; }
        public virtual ICollection<Event> Event { get; set; }
    }
}
