//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectsAssociation
    {
        public int ObjectsAssociationId { get; set; }
        public int Object1Identity { get; set; }
        public int Object2Identity { get; set; }
        public int ObjectTypeId { get; set; }
    
        public virtual ObjectType ObjectType { get; set; }
    }
}
