//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int ResourceId { get; set; }
        public string Description { get; set; }
        public string MimeType { get; set; }
        public int Size { get; set; }
        public string Uri { get; set; }
        public string DerefUri { get; set; }
        public string Digest { get; set; }
        public long InfoId { get; set; }
    
        public virtual Info Info { get; set; }
    }
}
