//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGeoFencingAlert
    {
        public int GeoFenceAlertID { get; set; }
        public long AlertId { get; set; }
        public string Type { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public string Direction { get; set; }
        public string IMEI { get; set; }
        public string Assetname { get; set; }
        public string Regno { get; set; }
        public string username { get; set; }
        public string Eventvalue { get; set; }
        public Nullable<System.DateTime> AlertDatetime { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> AlertDate { get; set; }
    }
}
