//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoAanalyticsEvent
    {
        public int VideoAanalyticsEventId { get; set; }
        public System.Guid CameraGuid { get; set; }
        public string ObjectId { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public int CenterX { get; set; }
        public int CenterY { get; set; }
        public System.DateTime SentTime { get; set; }
        public bool IsInZone { get; set; }
        public int AlarmLevel { get; set; }
        public string AlgorithmName { get; set; }
        public Nullable<long> AlertId { get; set; }
    
        public virtual Alert Alert { get; set; }
    }
}
