//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/21 - 11:57:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class InternalContactDetailsDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Int32 InterfaceID { get; set; }

        [DataMember()]
        public String ContactName { get; set; }

        [DataMember()]
        public String ContactNumber { get; set; }

        [DataMember()]
        public String ContactEmailid { get; set; }

        public InternalContactDetailsDTO()
        {
        }

        public InternalContactDetailsDTO(Int32 iD, Int32 interfaceID, String contactName, String contactNumber, String contactEmailid)
        {
			this.ID = iD;
			this.InterfaceID = interfaceID;
			this.ContactName = contactName;
			this.ContactNumber = contactNumber;
			this.ContactEmailid = contactEmailid;
        }
    }
}
