//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2018/03/29 - 17:51:44
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_ReturnAlertEscalationNotificationMember_ResultDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String IPAddress { get; set; }

        public SP_ReturnAlertEscalationNotificationMember_ResultDTO()
        {
        }

        public SP_ReturnAlertEscalationNotificationMember_ResultDTO(Int32 iD, String iPAddress)
        {
			this.ID = iD;
			this.IPAddress = iPAddress;
        }
    }
}
