//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/06/07 - 13:33:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_SWMRealtimebinfullalertKPI_ResultDTO
    {
        [DataMember()]
        public Nullable<int> TotalAlerts { get; set; }

        [DataMember()]
        public string MessageTypeID { get; set; }
    }
}
