//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/06/07 - 12:15:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_SWMVehicleLocNStatusKPI_ResultDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String VehicleNo { get; set; }

        [DataMember()]
        public String VehicleType { get; set; }

        [DataMember()]
        public String WardNo { get; set; }

        [DataMember()]
        public String SimNo { get; set; }

        [DataMember()]
        public String DriverName { get; set; }

        [DataMember()]
        public String DriverMobile { get; set; }

        [DataMember()]
        public Nullable<DateTime> Maxdatetime { get; set; }

        [DataMember()]
        public Int32 VehicleID { get; set; }

        [DataMember()]
        public String VehicleStatus { get; set; }

        [DataMember()]
        public Nullable<Double> Lat { get; set; }

        [DataMember()]
        public Nullable<Double> Long_ { get; set; }

        [DataMember()]
        public Nullable<Double> Angle { get; set; }

        [DataMember()]
        public String Ignition { get; set; }

        [DataMember()]
        public String Location { get; set; }

        [DataMember()]
        public Nullable<Int32> Speed { get; set; }

        [DataMember()]
        public String Status { get; set; }

        [DataMember()]
        public String VehicleStatusImage { get; set; }

        [DataMember()]
        public String VehicleStatusColour { get; set; }

        public SP_SWMVehicleLocNStatusKPI_ResultDTO()
        {
        }

        public SP_SWMVehicleLocNStatusKPI_ResultDTO(Int32 iD, String vehicleNo, String vehicleType, String wardNo, String simNo, String driverName, String driverMobile, Nullable<DateTime> maxdatetime, Int32 vehicleID, String vehicleStatus, Nullable<Double> lat, Nullable<Double> long_, Nullable<Double> angle, String ignition, String location, Nullable<Int32> speed, String status, String vehicleStatusImage, String vehicleStatusColour)
        {
            this.ID = iD;
            this.VehicleNo = vehicleNo;
            this.VehicleType = vehicleType;
            this.WardNo = wardNo;
            this.SimNo = simNo;
            this.DriverName = driverName;
            this.DriverMobile = driverMobile;
            this.Maxdatetime = maxdatetime;
            this.VehicleID = vehicleID;
            this.VehicleStatus = vehicleStatus;
            this.Lat = lat;
            this.Long_ = long_;
            this.Angle = angle;
            this.Ignition = ignition;
            this.Location = location;
            this.Speed = speed;
            this.Status = status;
            this.VehicleStatusImage = vehicleStatusImage;
            this.VehicleStatusColour = vehicleStatusColour;
        }
    }
}
