//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/21 - 20:38:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_WATMDashboardTypeCollection_ResultDTO
    {
        [DataMember()]
        public Nullable<Decimal> CardCollection { get; set; }

        [DataMember()]
        public Nullable<Decimal> CoinCollection { get; set; }

        public SP_WATMDashboardTypeCollection_ResultDTO()
        {
        }

        public SP_WATMDashboardTypeCollection_ResultDTO(Nullable<Decimal> cardCollection, Nullable<Decimal> coinCollection)
        {
			this.CardCollection = cardCollection;
			this.CoinCollection = coinCollection;
        }
    }
}
