//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/21 - 20:37:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_WATMDispenserDahsboardStatus_ResultDTO
    {
        [DataMember()]
        public Nullable<Int32> DispenserStatusCount { get; set; }

        [DataMember()]
        public String DispenserStatus { get; set; }

        public SP_WATMDispenserDahsboardStatus_ResultDTO()
        {
        }

        public SP_WATMDispenserDahsboardStatus_ResultDTO(Nullable<Int32> dispenserStatusCount, String dispenserStatus)
        {
			this.DispenserStatusCount = dispenserStatusCount;
			this.DispenserStatus = dispenserStatus;
        }
    }
}
