//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/17 - 19:06:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_WATMTCDashboardStatus_ResultDTO
    {
        [DataMember()]
        public Int64 DeviceId { get; set; }

        [DataMember()]
        public String WATMID { get; set; }

        [DataMember()]
        public String WATMStatus { get; set; }

        [DataMember()]
        public Nullable<DateTime> WATMStatusDatetime { get; set; }

        [DataMember()]
        public String DispenserID { get; set; }

        [DataMember()]
        public String DispenserStatus { get; set; }

        [DataMember()]
        public Nullable<DateTime> WDSatusdatetime { get; set; }

        public SP_WATMTCDashboardStatus_ResultDTO()
        {
        }

        public SP_WATMTCDashboardStatus_ResultDTO(Int64 deviceId, String wATMID, String wATMStatus, Nullable<DateTime> wATMStatusDatetime, String dispenserID, String dispenserStatus, Nullable<DateTime> wDSatusdatetime)
        {
            this.DeviceId = deviceId;
            this.WATMID = wATMID;
            this.WATMStatus = wATMStatus;
            this.WATMStatusDatetime = wATMStatusDatetime;
            this.DispenserID = dispenserID;
            this.DispenserStatus = dispenserStatus;
            this.WDSatusdatetime = wDSatusdatetime;
        }
    }
}
