//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/21 - 20:36:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_WATMDahsboardStatus_ResultDTO
    {
        [DataMember()]
        public Nullable<Int32> WATMStatusCount { get; set; }

        [DataMember()]
        public String WATMStatus { get; set; }

        public SP_WATMDahsboardStatus_ResultDTO()
        {
        }

        public SP_WATMDahsboardStatus_ResultDTO(Nullable<Int32> wATMStatusCount, String wATMStatus)
        {
			this.WATMStatusCount = wATMStatusCount;
			this.WATMStatus = wATMStatus;
        }
    }
}
