//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/03 - 15:35:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SubMemberDTO
    {
        [DataMember()]
        public Int32 MemID { get; set; }

        [DataMember()]
        public String AccountNumber { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Mobile { get; set; }

        [DataMember()]
        public Byte[] Photo { get; set; }

        [DataMember()]
        public Int64 DeviceID { get; set; }

        public SubMemberDTO()
        {
        }

        public SubMemberDTO(Int32 memID, String accountNumber, String name, String mobile, Byte[] photo, Int64 deviceID)
        {
			this.MemID = memID;
			this.AccountNumber = accountNumber;
			this.Name = name;
			this.Mobile = mobile;
			this.Photo = photo;
			this.DeviceID = deviceID;
        }
    }
}
