//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/11/18 - 16:13:31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblcustomermasterDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String title { get; set; }

        [DataMember()]
        public String firstname { get; set; }

        [DataMember()]
        public String lastname { get; set; }

        [DataMember()]
        public String contactnumber { get; set; }

        [DataMember()]
        public String emailid { get; set; }

        [DataMember()]
        public String ownership { get; set; }

        [DataMember()]
        public String CID { get; set; }

        public tblcustomermasterDTO()
        {
        }

        public tblcustomermasterDTO(Int32 iD, String title, String firstname, String lastname, String contactnumber, String emailid, String ownership, String cID)
        {
            this.ID = iD;
            this.title = title;
            this.firstname = firstname;
            this.lastname = lastname;
            this.contactnumber = contactnumber;
            this.emailid = emailid;
            this.ownership = ownership;
            this.CID = cID;
        }
    }
}
