//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/11/13 - 15:03:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblEscalationMatrixInfoDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Nullable<Int32> EscalationConfigMasterID { get; set; }

        [DataMember()]
        public String EscalationLevelName { get; set; }

        [DataMember()]
        public String EscalationContactDetails { get; set; }

        [DataMember()]
        public Nullable<Int32> EscalationTime { get; set; }

        [DataMember()]
        public Nullable<Int32> MessageTypeID { get; set; }

        [DataMember()]
        public Int32 tblEscalationConfigMaster_ID { get; set; }

        public EscalationContactDetailsDataDtoList EscalationContactDetailsDataDtoList { get; set; }

        public tblEscalationMatrixInfoDTO()
        {
        }

        public tblEscalationMatrixInfoDTO(Int32 iD, Nullable<Int32> escalationConfigMasterID, String escalationLevelName, String escalationContactDetails, Nullable<Int32> escalationTime, Nullable<Int32> messageTypeID, Int32 tblEscalationConfigMaster_ID, EscalationContactDetailsDataDtoList escalationContactDetailsDataDtoList)
        {
            this.ID = iD;
            this.EscalationConfigMasterID = escalationConfigMasterID;
            this.EscalationLevelName = escalationLevelName;
            this.EscalationContactDetails = escalationContactDetails;
            this.EscalationTime = escalationTime;
            this.MessageTypeID = messageTypeID;
            this.tblEscalationConfigMaster_ID = tblEscalationConfigMaster_ID;
            this.EscalationContactDetailsDataDtoList = escalationContactDetailsDataDtoList;
        }
    }

    public class EscalationContactDetailsDataDtoList
    {
        public List<EscalationContactDetailsDataContactDto> Contact { get; set; }
    }

    public class EscalationContactDetailsDataContactDto
    {
        public int EmergencyContactTableId { get; set; }

        public bool IsCustomContact { get; set; }

        public string ContactName { get; set; }

        public string ContactNumber { get; set; }

        public string ContactEmail { get; set; }

        public bool IsSendTextMessage { get; set; }

        public bool IsSendEmail { get; set; }

        public bool IsSendMobileNotification { get; set; }
    }
}
