//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/11/13 - 15:03:48
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblEscalationConfigDetailsDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Nullable<Int32> EscalationConfigMasterID { get; set; }

        [DataMember()]
        public Nullable<Int32> SiteID { get; set; }

        [DataMember()]
        public Nullable<Int32> InterfaceID { get; set; }

        [DataMember()]
        public Nullable<Int32> AreaID { get; set; }

        [DataMember()]
        public Nullable<Int32> FloorID { get; set; }

        [DataMember()]
        public Nullable<Int32> ZoneID { get; set; }

        [DataMember()]
        public Nullable<Int64> DeviceID { get; set; }

        [DataMember()]
        public String Eventcode_Severity { get; set; }

        [DataMember()]
        public Int32 tblEscalationConfigMaster_ID { get; set; }

        [DataMember()]
        public String Eventcode { get; set; }

        [DataMember()]
        public String Severity { get; set; }

        public tblEscalationConfigDetailsDTO()
        {
        }

        public tblEscalationConfigDetailsDTO(Int32 iD, Nullable<Int32> escalationConfigMasterID, Nullable<Int32> siteID, Nullable<Int32> interfaceID, Nullable<Int32> areaID, Nullable<Int32> floorID, Nullable<Int32> zoneID, Nullable<Int64> deviceID, String eventcode_Severity, Int32 tblEscalationConfigMaster_ID, String eventcode)
        {
            this.ID = iD;
            this.EscalationConfigMasterID = escalationConfigMasterID;
            this.SiteID = siteID;
            this.InterfaceID = interfaceID;
            this.AreaID = areaID;
            this.FloorID = floorID;
            this.ZoneID = zoneID;
            this.DeviceID = deviceID;
            this.Eventcode_Severity = eventcode_Severity;
            this.tblEscalationConfigMaster_ID = tblEscalationConfigMaster_ID;
            this.Eventcode = eventcode;
        }
    }
}
