//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2018/01/12 - 20:46:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblEnvironmentthresholdDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String SensorType { get; set; }

        [DataMember()]
        public String SensorID { get; set; }

        [DataMember()]
        public Nullable<Decimal> ThresholdValue { get; set; }

        public tblEnvironmentthresholdDTO()
        {
        }

        public tblEnvironmentthresholdDTO(Int32 iD, String sensorType, Nullable<Decimal> thresholdValue,String sensorID)
        {
			this.ID = iD;
			this.SensorType = sensorType;
			this.ThresholdValue = thresholdValue;
            this.SensorID = sensorID;
        }
    }
}
