//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2018/05/03 - 14:34:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblMachineStatusDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String MachineName { get; set; }

        [DataMember()]
        public String IPAddress { get; set; }

        [DataMember()]
        public String Port { get; set; }

        [DataMember()]
        public String ServiceName { get; set; }

        [DataMember()]
        public Int32 UpdateFlag { get; set; }

        public tblMachineStatusDTO()
        {
        }

        public tblMachineStatusDTO(Int32 iD, String machineName, String iPAddress, String port, String serviceName, Int32 updateFlag)
        {
			this.ID = iD;
			this.MachineName = machineName;
			this.IPAddress = iPAddress;
			this.Port = port;
			this.ServiceName = serviceName;
			this.UpdateFlag = updateFlag;
        }
    }
}
