//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2018/04/13 - 15:08:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblMultiviewTemplateDto
    {
        [DataMember()]
        public long Id { get; set; }

        [DataMember()]
        public Nullable<int> DeviceId { get; set; }

        [DataMember()]
        public Nullable<int> AssociateviewDeviceId { get; set; }

        [DataMember()]
        public int InOrder { get; set; }

        [DataMember()]
        public String Remark { get; set; }

        [DataMember()]
        public String TemplateName { get; set; }

        [DataMember()]
        public String CameraIP { get; set; }

        public tblMultiviewTemplateDto()
        {
        }

        public tblMultiviewTemplateDto(int id, Nullable<int> deviceId, Nullable<int> associateviewDeviceId, int inOrder, String remark, String templateName, String cameraIP)
        {
            this.Id = id;
            this.DeviceId = deviceId;
            this.AssociateviewDeviceId = associateviewDeviceId;
            this.InOrder = inOrder;
            this.Remark = remark;
            this.TemplateName = templateName;
            this.CameraIP = cameraIP;
        }
    }
}
