//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/02/13 - 12:04:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblMagosRadarMasterDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Nullable<Guid> RadarUID { get; set; }

        [DataMember()]
        public String RadarColor { get; set; }

        [DataMember()]
        public Nullable<Boolean> RadarConnectionStatus { get; set; }

        [DataMember()]
        public String RadarIPPort { get; set; }

        [DataMember()]
        public String RadarName { get; set; }

        [DataMember()]
        public String RadarState { get; set; }

        [DataMember()]
        public String RadarType { get; set; }

        [DataMember()]
        public Nullable<Double> Lat { get; set; }

        [DataMember()]
        public Nullable<Double> Long_ { get; set; }

        [DataMember()]
        public Nullable<Double> RadarAngel { get; set; }

        public tblMagosRadarMasterDTO()
        {
        }

        public tblMagosRadarMasterDTO(Int32 iD, Nullable<Guid> radarUID, String radarColor, Nullable<Boolean> radarConnectionStatus, String radarIPPort, String radarName, String radarState, String radarType, Nullable<Double> lat, Nullable<Double> long_, Nullable<Double> radarAngel)
        {
            this.ID = iD;
            this.RadarUID = radarUID;
            this.RadarColor = radarColor;
            this.RadarConnectionStatus = radarConnectionStatus;
            this.RadarIPPort = radarIPPort;
            this.RadarName = radarName;
            this.RadarState = radarState;
            this.RadarType = radarType;
            this.Lat = lat;
            this.Long_ = long_;
            this.RadarAngel = radarAngel;
        }
    }
}
