//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/02/13 - 12:05:18
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblMagosTrackingDataDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Nullable<Int32> RadarMasterID { get; set; }

        [DataMember()]
        public Nullable<Double> Angle { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> LastupdateTime { get; set; }

        [DataMember()]
        public Nullable<Guid> RadarUID { get; set; }

        [DataMember()]
        public String TrackingID { get; set; }

        [DataMember()]
        public Nullable<Double> Lat { get; set; }

        [DataMember()]
        public Nullable<Double> Long_ { get; set; }

        [DataMember()]
        public Nullable<Int32> TrackState { get; set; }

        public tblMagosTrackingDataDTO()
        {
        }

        public tblMagosTrackingDataDTO(Int32 iD, Nullable<Int32> radarMasterID, Nullable<Double> angle, Nullable<DateTime> creationTime, Nullable<DateTime> lastupdateTime, Nullable<Guid> radarUID, String trackingID, Nullable<Double> lat, Nullable<Double> long_, Nullable<Int32> trackState)
        {
            this.ID = iD;
            this.RadarMasterID = radarMasterID;
            this.Angle = angle;
            this.CreationTime = creationTime;
            this.LastupdateTime = lastupdateTime;
            this.RadarUID = radarUID;
            this.TrackingID = trackingID;
            this.Lat = lat;
            this.Long_ = long_;
            this.TrackState = trackState;
        }
    }
}
