//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2018/08/22 - 21:53:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblOLTMasterDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String SoftwareVersion { get; set; }

        [DataMember()]
        public String IPaddress { get; set; }

        [DataMember()]
        public String OLTName { get; set; }

        [DataMember()]
        public String OLTTRole { get; set; }

        [DataMember()]
        public String OLTSupervisionStatus { get; set; }

        public tblOLTMasterDTO()
        {
        }

        public tblOLTMasterDTO(Int32 iD, String softwareVersion, String iPaddress, String oLTName, String oLTTRole, String oLTSupervisionStatus)
        {
            this.ID = iD;
            this.SoftwareVersion = softwareVersion;
            this.IPaddress = iPaddress;
            this.OLTName = oLTName;
            this.OLTTRole = oLTTRole;
            this.OLTSupervisionStatus = oLTSupervisionStatus;
        }
    }
}
