//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2018/12/07 - 11:19:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblPanelMasterDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String PanelMake { get; set; }

        [DataMember()]
        public String PanelModel { get; set; }

        [DataMember()]
        public String Description { get; set; }

        public tblPanelMasterDTO()
        {
        }

        public tblPanelMasterDTO(Int32 iD, String panelMake, String panelModel, String description)
        {
            this.ID = iD;
            this.PanelMake = panelMake;
            this.PanelModel = panelModel;
            this.Description = description;
        }
    }
}
