//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/06/01 - 19:43:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblPidsDevicelocationInfoDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Int32 PidsDeviceID { get; set; }

        [DataMember()]
        public Double lat { get; set; }

        [DataMember()]
        public Double long_ { get; set; }

        public tblPidsDevicelocationInfoDTO()
        {
        }

        public tblPidsDevicelocationInfoDTO(Int32 iD, Int32 pidsDeviceID, Double lat, Double long_)
        {
            this.ID = iD;
            this.PidsDeviceID = pidsDeviceID;
            this.lat = lat;
            this.long_ = long_;
        }
    }
}
