//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/08/27 - 10:25:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblRssAlertMasterDto
    {
        [DataMember()]
        public Int32 RssfeebackID { get; set; }

        [DataMember()]
        public String NegativeComments { get; set; }

        public tblRssAlertMasterDto()
        {
        }

        public tblRssAlertMasterDto(Int32 rssfeebackID, String negativeComments)
        {
			this.RssfeebackID = rssfeebackID;
			this.NegativeComments = negativeComments;
        }
    }
}
