//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/03/07 - 16:12:37
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblSOPMasterDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String SOPName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Int32 SOPTypeID { get; set; }

        [DataMember()]
        public Int32 SOPInputTypeID { get; set; }

        [DataMember()]
        public String SOPAction { get; set; }

        [DataMember()]
        public String SOPInputTypeName { get; set; }

        [DataMember()]
        public String SOPTriggerCondition { get; set; }

        public tblSOPMasterDTO()
        {
        }

        public tblSOPMasterDTO(Int32 iD, String sOPName, String description, Int32 sOPTypeID, Int32 sOPInputTypeID, String sOPAction, String sOPTriggerCondition)
        {
			this.ID = iD;
			this.SOPName = sOPName;
			this.Description = description;
			this.SOPTypeID = sOPTypeID;
			this.SOPInputTypeID = sOPInputTypeID;
            this.SOPAction = sOPAction;
            this.SOPTriggerCondition = sOPTriggerCondition;
        }
    }
}
