//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/10/11 - 20:14:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblSMSConfigurationDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String Url { get; set; }

        [DataMember()]
        public string Name { get; set; }

        public tblSMSConfigurationDTO()
        {
        }

        public tblSMSConfigurationDTO(Int32 iD, String url, string name)
        {
			this.ID = iD;
			this.Url = url;
            this.Name = name;
        }
    }
}
