//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/08/26 - 20:59:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblUserSiteMasterDto
    {
        [DataMember()]
        public Int32 UserSiteID { get; set; }

        [DataMember()]
        public String UserID { get; set; }

        [DataMember()]
        public String SiteID { get; set; }

        [DataMember()]
        public String UserType { get; set; }

        public tblUserSiteMasterDto()
        {

        }

        public tblUserSiteMasterDto(Int32 userSiteID, String userID, String siteID, String userType)
        {
            this.UserSiteID = userSiteID;
            this.UserID = userID;
            this.SiteID = siteID;
            this.UserType = userType;
        }
    }
}
