//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/11 - 16:09:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblWATMCollectionDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String DeviceId { get; set; }

        [DataMember()]
        public String DispenserCollection { get; set; }

        [DataMember()]
        public String CoinCollection { get; set; }

        [DataMember()]
        public String CardCollection { get; set; }

        [DataMember()]
        public String QtyDispensed { get; set; }

        [DataMember()]
        public String TotalCollection { get; set; }

        [DataMember()]
        public String GoogleCityName { get; set; }

        [DataMember()]
        public String Latitude { get; set; }

        [DataMember()]
        public String Longtitude { get; set; }

        [DataMember()]
        public String D1 { get; set; }

        [DataMember()]
        public String D2 { get; set; }

        [DataMember()]
        public String D3 { get; set; }

        [DataMember()]
        public String D4 { get; set; }

        [DataMember()]
        public String D5 { get; set; }

        [DataMember()]
        public Nullable<DateTime> TxnDateTime { get; set; }

        public tblWATMCollectionDTO()
        {
        }

        public tblWATMCollectionDTO(Int32 iD, String deviceId, String dispenserCollection, String coinCollection, String cardCollection, String qtyDispensed, String totalCollection, String googleCityName, String latitude, String longtitude, String d1, String d2, String d3, String d4, String d5, Nullable<DateTime> txnDateTime)
        {
            this.ID = iD;
            this.DeviceId = deviceId;
            this.DispenserCollection = dispenserCollection;
            this.CoinCollection = coinCollection;
            this.CardCollection = cardCollection;
            this.QtyDispensed = qtyDispensed;
            this.TotalCollection = totalCollection;
            this.GoogleCityName = googleCityName;
            this.Latitude = latitude;
            this.Longtitude = longtitude;
            this.D1 = d1;
            this.D2 = d2;
            this.D3 = d3;
            this.D4 = d4;
            this.D5 = d5;
            this.TxnDateTime = txnDateTime;
        }
    }
}
