//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/11 - 16:10:41
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblWATMStatusDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String DeviceId { get; set; }

        [DataMember()]
        public String Status { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdatedTime { get; set; }

        public tblWATMStatusDTO()
        {
        }

        public tblWATMStatusDTO(Int32 iD, String deviceId, String status, Nullable<DateTime> updatedTime)
        {
            this.ID = iD;
            this.DeviceId = deviceId;
            this.Status = status;
            this.UpdatedTime = updatedTime;
        }
    }
}
