//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/03/26 - 14:18:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class AccountTypeDto
    {
        [DataMember()]
        public Int32 AccoutTypeId { get; set; }

        [DataMember()]
        public String AccountTypeName { get; set; }

        [DataMember()]
        public Boolean SiteEventReport { get; set; }

        [DataMember()]
        public Int32 ReportDeliveryMethodId { get; set; }

        [DataMember()]
        public Boolean OpenCloseMonitoring { get; set; }

        [DataMember()]
        public Boolean DailyOpenCloseReports { get; set; }

        [DataMember()]
        public Boolean WeeklyOpenCloseReporting { get; set; }

        [DataMember()]
        public Boolean SMS { get; set; }

        //[DataMember()]
        public DeliveryMethodDto DeliveryMethod { get; set; }

        public AccountTypeDto()
        {
        }
    }
}
