//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/01/17 - 10:06:13
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class BioAlertsDTO
    {
        [DataMember()]
        public Int32 BioAlertID { get; set; }

        [DataMember()]
        public String Type { get; set; }

        [DataMember()]
        public DateTime TimeStamp { get; set; }

        [DataMember()]
        public String CameraId { get; set; }

        [DataMember()]
        public Int32 Quality { get; set; }

        [DataMember()]
        public Int32 Score { get; set; }

        [DataMember()]
        public Byte[] FrameImage { get; set; }

        [DataMember()]
        public Int32 FrameIndex { get; set; }

        [DataMember()]
        public Int32 FaceSize { get; set; }

        [DataMember()]
        public String FacePosition { get; set; }

        [DataMember()]
        public Byte[] SubjectFaceImage { get; set; }

        [DataMember()]
        public Byte[] SubjectModelImage { get; set; }

        [DataMember()]
        public Int32 SubjectId { get; set; }

        [DataMember()]
        public String SubjectCode { get; set; }

        [DataMember()]
        public String SubjectName { get; set; }

        [DataMember()]
        public String SubjectLastName { get; set; }

        [DataMember()]
        public Nullable<Int64> alertID { get; set; }
        
        public BioAlertsDTO()
        {
        }

        public BioAlertsDTO(Int32 bioAlertID, String type, DateTime timeStamp, String cameraId, Int32 quality, Int32 score, Byte[] frameImage, Int32 frameIndex, Int32 faceSize, String facePosition, Byte[] subjectFaceImage, Byte[] subjectModelImage, Int32 subjectId, String subjectCode, String subjectName, String subjectLastName, Nullable<Int64> alertID)
        {
			this.BioAlertID = bioAlertID;
			this.Type = type;
			this.TimeStamp = timeStamp;
			this.CameraId = cameraId;
			this.Quality = quality;
			this.Score = score;
			this.FrameImage = frameImage;
			this.FrameIndex = frameIndex;
			this.FaceSize = faceSize;
			this.FacePosition = facePosition;
			this.SubjectFaceImage = subjectFaceImage;
			this.SubjectModelImage = subjectModelImage;
			this.SubjectId = subjectId;
			this.SubjectCode = subjectCode;
			this.SubjectName = subjectName;
			this.SubjectLastName = subjectLastName;
			this.alertID = alertID;
        }
    }
}
