//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/05/24 - 14:59:50
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract(), KnownType(typeof(EventCodeDto))]
    public partial class EventGroupDto
    {
        [DataMember()]
        public Int32 EventGroupId { get; set; }

        [DataMember()]
        public Int32 EventCodeMin { get; set; }

        [DataMember()]
        public Int32 EventCodeMax { get; set; }

        [DataMember()]
        public String EventCodeGroupDescription { get; set; }

        [DataMember]
        public List<EventCodeDto> EventCodeCollection { get; set; }
    }
}
