//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/05/24 - 14:59:50
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class EventQualifierDto
    {
        [DataMember()]
        public Int32 EventQualifierId { get; set; }

        [DataMember()]
        public String EventQualifierDescription { get; set; }

        public EventQualifierDto()
        {
        }

        public EventQualifierDto(Int32 eventQualifierId, String eventQualifierDescription)
        {
			this.EventQualifierId = eventQualifierId;
			this.EventQualifierDescription = eventQualifierDescription;
        }
    }
}
