//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/05/27 - 14:35:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class EventFieldTypeDto
    {
        [DataMember()]
        public Int32 FieldTypeId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Format { get; set; }

        [DataMember()]
        public List<EventFieldDefinitionDto> EventFieldDefinition { get; set; }
    }
}
