//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/21 - 11:31:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblGeoFencingHistoryDTO
    {
        [DataMember()]
        public Int32 GeoFenceHistoryID { get; set; }

        [DataMember()]
        public Int64 DeviceId { get; set; }

        [DataMember()]
        public Nullable<Int64> AlertId { get; set; }

        [DataMember()]
        public Nullable<Double> Lat { get; set; }

        [DataMember()]
        public Nullable<Double> Long_ { get; set; }

        [DataMember()]
        public Nullable<DateTime> DateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDate { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDate { get; set; }

        [DataMember()]
        public String Heading { get; set; }

        [DataMember()]
        public String Speed { get; set; }

        [DataMember()]
        public String Location { get; set; }

        [DataMember()]
        public String Status { get; set; }

        [DataMember()]
        public String Battery { get; set; }

        [DataMember()]
        public String Asset { get; set; }

        [DataMember()]
        public Nullable<Int32> Eventno { get; set; }

        [DataMember()]
        public String Eventname { get; set; }

        [DataMember()]
        public String Legend { get; set; }

        [DataMember()]
        public String Remark { get; set; }

        [DataMember()]
        public String Remarkdate { get; set; }

        [DataMember()]
        public String Tripname { get; set; }

        [DataMember()]
        public String Distance { get; set; }

        [DataMember()]
        public String User { get; set; }

        public tblGeoFencingHistoryDTO()
        {
        }

        public tblGeoFencingHistoryDTO(Int32 geoFenceHistoryID, Int64 deviceId, Nullable<Int64> alertId, Nullable<Double> lat, Nullable<Double> long_, Nullable<DateTime> dateTime, Nullable<DateTime> startDate, Nullable<DateTime> endDate, String heading, String speed, String location, String status, String battery, String asset, Nullable<Int32> eventno, String eventname, String legend, String remark, String remarkdate, String tripname, String distance, String user)
        {
            this.GeoFenceHistoryID = geoFenceHistoryID;
            this.DeviceId = deviceId;
            this.AlertId = alertId;
            this.Lat = lat;
            this.Long_ = long_;
            this.DateTime = dateTime;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.Heading = heading;
            this.Speed = speed;
            this.Location = location;
            this.Status = status;
            this.Battery = battery;
            this.Asset = asset;
            this.Eventno = eventno;
            this.Eventname = eventname;
            this.Legend = legend;
            this.Remark = remark;
            this.Remarkdate = remarkdate;
            this.Tripname = tripname;
            this.Distance = distance;
            this.User = user;
        }
    }
}
