//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/11/18 - 17:54:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblNokDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsAlert { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsLoop { get; set; }

        public tblNokDTO()
        {
        }

        public tblNokDTO(Int32 iD, String name, String description, Nullable<Boolean> isAlert, Nullable<Boolean> isLoop)
        {
			this.ID = iD;
			this.Name = name;
			this.Description = description;
			this.IsAlert = isAlert;
			this.IsLoop = isLoop;
        }
    }
}
