//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.WatchDogService.AlertProcessingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://2020imaging.com/biztalk", ConfigurationName="AlertProcessingServiceReference.AlertProcessingService")]
    public interface AlertProcessingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Process", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessResponse Process(AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Process", ReplyAction="*")]
        System.IAsyncResult BeginProcess(AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessRequest request, System.AsyncCallback callback, object asyncState);
        
        AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessResponse EndProcess(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://2020imaging.com/schema/BizTalk")]
    public partial class Alert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressesField;
        
        private ushort alertIdField;
        
        private string authTokenField;
        
        private string codeField;
        
        private string identifierField;
        
        private string incidentsField;
        
        private string workflowStatusField;
        
        private AlertInfo[] infoCollectionField;
        
        private string messageTypeIdField;
        
        private string noteField;
        
        private string referencesField;
        
        private string restrictionField;
        
        private string scopeIdField;
        
        private string senderField;
        
        private string sentAsStringField;
        
        private string sourceField;
        
        private string statusIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("Addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ushort AlertId {
            get {
                return this.alertIdField;
            }
            set {
                this.alertIdField = value;
                this.RaisePropertyChanged("AlertId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AuthToken {
            get {
                return this.authTokenField;
            }
            set {
                this.authTokenField = value;
                this.RaisePropertyChanged("AuthToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Incidents {
            get {
                return this.incidentsField;
            }
            set {
                this.incidentsField = value;
                this.RaisePropertyChanged("Incidents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string WorkflowStatus {
            get {
                return this.workflowStatusField;
            }
            set {
                this.workflowStatusField = value;
                this.RaisePropertyChanged("WorkflowStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Info", IsNullable=false)]
        public AlertInfo[] InfoCollection {
            get {
                return this.infoCollectionField;
            }
            set {
                this.infoCollectionField = value;
                this.RaisePropertyChanged("InfoCollection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MessageTypeId {
            get {
                return this.messageTypeIdField;
            }
            set {
                this.messageTypeIdField = value;
                this.RaisePropertyChanged("MessageTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string References {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
                this.RaisePropertyChanged("References");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Restriction {
            get {
                return this.restrictionField;
            }
            set {
                this.restrictionField = value;
                this.RaisePropertyChanged("Restriction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ScopeId {
            get {
                return this.scopeIdField;
            }
            set {
                this.scopeIdField = value;
                this.RaisePropertyChanged("ScopeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string SentAsString {
            get {
                return this.sentAsStringField;
            }
            set {
                this.sentAsStringField = value;
                this.RaisePropertyChanged("SentAsString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("StatusId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://2020imaging.com/schema/BizTalk")]
    public partial class AlertInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort alertIdField;
        
        private AlertInfoArea[] areasCollectionField;
        
        private string audienceField;
        
        private string[] categoriesCollectionField;
        
        private string certaintyIdField;
        
        private string contactField;
        
        private string descriptionField;
        
        private string effectiveField;
        
        private string eventField;
        
        private AlertInfoEventCode[] eventCodesCollectionField;
        
        private string expiresField;
        
        private string headlineField;
        
        private uint infoIdField;
        
        private string instructionField;
        
        private string languageField;
        
        private string onSetField;
        
        private AlertInfoParameter[] parametersCollectionField;
        
        private AlertInfoResource[] resourcesCollectionField;
        
        private string[] responseTypesCollectionField;
        
        private string senderNameField;
        
        private string severityIdField;
        
        private string urgencyIdField;
        
        private string webField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ushort AlertId {
            get {
                return this.alertIdField;
            }
            set {
                this.alertIdField = value;
                this.RaisePropertyChanged("AlertId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Area", IsNullable=false)]
        public AlertInfoArea[] AreasCollection {
            get {
                return this.areasCollectionField;
            }
            set {
                this.areasCollectionField = value;
                this.RaisePropertyChanged("AreasCollection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Audience {
            get {
                return this.audienceField;
            }
            set {
                this.audienceField = value;
                this.RaisePropertyChanged("Audience");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Category", IsNullable=false)]
        public string[] CategoriesCollection {
            get {
                return this.categoriesCollectionField;
            }
            set {
                this.categoriesCollectionField = value;
                this.RaisePropertyChanged("CategoriesCollection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CertaintyId {
            get {
                return this.certaintyIdField;
            }
            set {
                this.certaintyIdField = value;
                this.RaisePropertyChanged("CertaintyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Effective {
            get {
                return this.effectiveField;
            }
            set {
                this.effectiveField = value;
                this.RaisePropertyChanged("Effective");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
                this.RaisePropertyChanged("Event");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EventCode", IsNullable=false)]
        public AlertInfoEventCode[] EventCodesCollection {
            get {
                return this.eventCodesCollectionField;
            }
            set {
                this.eventCodesCollectionField = value;
                this.RaisePropertyChanged("EventCodesCollection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Headline {
            get {
                return this.headlineField;
            }
            set {
                this.headlineField = value;
                this.RaisePropertyChanged("Headline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public uint InfoId {
            get {
                return this.infoIdField;
            }
            set {
                this.infoIdField = value;
                this.RaisePropertyChanged("InfoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Instruction {
            get {
                return this.instructionField;
            }
            set {
                this.instructionField = value;
                this.RaisePropertyChanged("Instruction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string OnSet {
            get {
                return this.onSetField;
            }
            set {
                this.onSetField = value;
                this.RaisePropertyChanged("OnSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable=false)]
        public AlertInfoParameter[] ParametersCollection {
            get {
                return this.parametersCollectionField;
            }
            set {
                this.parametersCollectionField = value;
                this.RaisePropertyChanged("ParametersCollection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Resource", IsNullable=false)]
        public AlertInfoResource[] ResourcesCollection {
            get {
                return this.resourcesCollectionField;
            }
            set {
                this.resourcesCollectionField = value;
                this.RaisePropertyChanged("ResourcesCollection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ResponseType", IsNullable=false)]
        public string[] ResponseTypesCollection {
            get {
                return this.responseTypesCollectionField;
            }
            set {
                this.responseTypesCollectionField = value;
                this.RaisePropertyChanged("ResponseTypesCollection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SenderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
                this.RaisePropertyChanged("SenderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string SeverityId {
            get {
                return this.severityIdField;
            }
            set {
                this.severityIdField = value;
                this.RaisePropertyChanged("SeverityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string UrgencyId {
            get {
                return this.urgencyIdField;
            }
            set {
                this.urgencyIdField = value;
                this.RaisePropertyChanged("UrgencyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
                this.RaisePropertyChanged("Web");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://2020imaging.com/schema/BizTalk")]
    public partial class AlertInfoArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal altitudeField;
        
        private ushort areaIdField;
        
        private decimal celingField;
        
        private string descriptionField;
        
        private uint infoIdField;
        
        private decimal latitudeField;
        
        private decimal longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
                this.RaisePropertyChanged("Altitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ushort AreaId {
            get {
                return this.areaIdField;
            }
            set {
                this.areaIdField = value;
                this.RaisePropertyChanged("AreaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Celing {
            get {
                return this.celingField;
            }
            set {
                this.celingField = value;
                this.RaisePropertyChanged("Celing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public uint InfoId {
            get {
                return this.infoIdField;
            }
            set {
                this.infoIdField = value;
                this.RaisePropertyChanged("InfoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://2020imaging.com/schema/BizTalk")]
    public partial class AlertInfoEventCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://2020imaging.com/schema/BizTalk")]
    public partial class AlertInfoParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://2020imaging.com/schema/BizTalk")]
    public partial class AlertInfoResource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string derefUriField;
        
        private string descriptionField;
        
        private string digestField;
        
        private byte infoIdField;
        
        private string mimeTypeField;
        
        private byte resourceIdField;
        
        private ushort sizeField;
        
        private string uriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DerefUri {
            get {
                return this.derefUriField;
            }
            set {
                this.derefUriField = value;
                this.RaisePropertyChanged("DerefUri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Digest {
            get {
                return this.digestField;
            }
            set {
                this.digestField = value;
                this.RaisePropertyChanged("Digest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public byte InfoId {
            get {
                return this.infoIdField;
            }
            set {
                this.infoIdField = value;
                this.RaisePropertyChanged("InfoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("MimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte ResourceId {
            get {
                return this.resourceIdField;
            }
            set {
                this.resourceIdField = value;
                this.RaisePropertyChanged("ResourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ushort Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("Uri");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://2020imaging.com/schema/BizTalk", Order=0)]
        public AMS.Broker.WatchDogService.AlertProcessingServiceReference.Alert Alert;
        
        public ProcessRequest() {
        }
        
        public ProcessRequest(AMS.Broker.WatchDogService.AlertProcessingServiceReference.Alert Alert) {
            this.Alert = Alert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessResponse {
        
        public ProcessResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlertProcessingServiceChannel : AMS.Broker.WatchDogService.AlertProcessingServiceReference.AlertProcessingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlertProcessingServiceClient : System.ServiceModel.ClientBase<AMS.Broker.WatchDogService.AlertProcessingServiceReference.AlertProcessingService>, AMS.Broker.WatchDogService.AlertProcessingServiceReference.AlertProcessingService {
        
        private BeginOperationDelegate onBeginProcessDelegate;
        
        private EndOperationDelegate onEndProcessDelegate;
        
        private System.Threading.SendOrPostCallback onProcessCompletedDelegate;
        
        public AlertProcessingServiceClient() {
        }
        
        public AlertProcessingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlertProcessingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlertProcessingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlertProcessingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ProcessCompletedEventArgs> ProcessCompleted;
        
        public AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessResponse Process(AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessRequest request) {
            return base.Channel.Process(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginProcess(AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginProcess(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessResponse EndProcess(System.IAsyncResult result) {
            return base.Channel.EndProcess(result);
        }
        
        private System.IAsyncResult OnBeginProcess(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessRequest request = ((AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessRequest)(inValues[0]));
            return this.BeginProcess(request, callback, asyncState);
        }
        
        private object[] OnEndProcess(System.IAsyncResult result) {
            AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessResponse retVal = this.EndProcess(result);
            return new object[] {
                    retVal};
        }
        
        private void OnProcessCompleted(object state) {
            if ((this.ProcessCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ProcessCompleted(this, new ProcessCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ProcessAsync(AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessRequest request) {
            this.ProcessAsync(request, null);
        }
        
        public void ProcessAsync(AMS.Broker.WatchDogService.AlertProcessingServiceReference.ProcessRequest request, object userState) {
            if ((this.onBeginProcessDelegate == null)) {
                this.onBeginProcessDelegate = new BeginOperationDelegate(this.OnBeginProcess);
            }
            if ((this.onEndProcessDelegate == null)) {
                this.onEndProcessDelegate = new EndOperationDelegate(this.OnEndProcess);
            }
            if ((this.onProcessCompletedDelegate == null)) {
                this.onProcessCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProcessCompleted);
            }
            base.InvokeAsync(this.onBeginProcessDelegate, new object[] {
                        request}, this.onEndProcessDelegate, this.onProcessCompletedDelegate, userState);
        }
    }
}
