//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long AuditLogId { get; set; }
        public System.DateTime ActivityDateTime { get; set; }
        public string AuditTypeId { get; set; }
        public string UserId { get; set; }
        public string SourceId { get; set; }
        public string SourceType { get; set; }
        public string Description { get; set; }
    
        public virtual AuditType AuditType { get; set; }
    }
}
