//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComparisonOperation
    {
        public ComparisonOperation()
        {
            this.AlertTemplateCondition = new HashSet<AlertTemplateCondition>();
        }
    
        public int ComparisonOperationId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AlertTemplateCondition> AlertTemplateCondition { get; set; }
    }
}
