//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoBox
    {
        public int objectId { get; set; }
        public int objectTypeId { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public decimal Alt { get; set; }
    
        public virtual SiteType SiteType { get; set; }
    }
}
