//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblANPRMaster
    {
        public int ANPRID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string ANPRCameraName { get; set; }
        public string appkey { get; set; }
    }
}
