//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDisasterMap
    {
        public int ID { get; set; }
        public string RescueType { get; set; }
        public Nullable<double> lon { get; set; }
        public string Lat { get; set; }
        public Nullable<double> Deg { get; set; }
    }
}
