//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModuleFieldMaster1
    {
        public int ModuleFieldID { get; set; }
        public int ModuleID { get; set; }
        public string FieldName { get; set; }
    
        public virtual tblModuleMaster1 tblModuleMaster { get; set; }
    }
}
