//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModuleMaster1
    {
        public tblModuleMaster1()
        {
            this.tblModuleFieldMaster = new HashSet<tblModuleFieldMaster1>();
        }
    
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
    
        public virtual ICollection<tblModuleFieldMaster1> tblModuleFieldMaster { get; set; }
    }
}
