//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblweatherchcurrent
    {
        public int ID { get; set; }
        public string CityName { get; set; }
        public string WeatherType { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
        public string Observation_Time { get; set; }
        public Nullable<int> ObservationTime { get; set; }
        public string Local_Time { get; set; }
        public Nullable<int> LocalTime { get; set; }
        public string Weather { get; set; }
        public Nullable<double> currenttemp { get; set; }
        public string currenthumidity { get; set; }
        public string wind_string { get; set; }
        public string Winddirection { get; set; }
        public Nullable<double> windblow { get; set; }
        public Nullable<double> pressure { get; set; }
        public Nullable<double> dewpoint { get; set; }
        public Nullable<double> heatindex { get; set; }
        public Nullable<double> visibility { get; set; }
        public Nullable<double> Precipitation { get; set; }
        public Nullable<double> feelslike { get; set; }
        public Nullable<double> UV { get; set; }
        public int AlertID { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public Nullable<System.DateTime> CurrentDateTime { get; set; }
        public string Icon { get; set; }
        public string Icon_url { get; set; }
    }
}
