//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeatherhourlyforecast
    {
        public int ID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<System.DateTime> ForecastDate { get; set; }
        public Nullable<System.DateTime> ForecastDateTime { get; set; }
        public Nullable<int> Epoc { get; set; }
        public string Pretty { get; set; }
        public Nullable<double> Temp { get; set; }
        public Nullable<double> Dewpoint { get; set; }
        public string Condition { get; set; }
        public string Icon { get; set; }
        public string Icon_URL { get; set; }
        public Nullable<int> Fctcode { get; set; }
        public string Sky { get; set; }
        public Nullable<double> WindSpeed { get; set; }
        public Nullable<double> WindDirection { get; set; }
        public string WindName { get; set; }
        public Nullable<int> UV { get; set; }
        public Nullable<double> HeatIndex { get; set; }
        public Nullable<double> Feelslike { get; set; }
        public Nullable<double> QPF { get; set; }
        public Nullable<double> Snow { get; set; }
        public Nullable<int> POP { get; set; }
        public Nullable<double> MSLP { get; set; }
        public int AlertID { get; set; }
    }
}
