//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeatherchforecast
    {
        public int ID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<System.DateTime> ForecastDate { get; set; }
        public Nullable<int> ForecastPeriod { get; set; }
        public string ForeCastDay { get; set; }
        public string ForecastIcon { get; set; }
        public string ForecastIconurl { get; set; }
        public string Daytitle { get; set; }
        public string ForecastText { get; set; }
        public Nullable<int> POP { get; set; }
        public Nullable<int> AlertID { get; set; }
    }
}
