//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="RuleEngineBinding", Namespace="http://www.onvif.org/ver20/analytics/wsdl")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageDescription))]
public partial class RuleEngineBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetSupportedRulesOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateRulesOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteRulesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetRulesOperationCompleted;
    
    private System.Threading.SendOrPostCallback ModifyRulesOperationCompleted;
    
    /// <remarks/>
    public RuleEngineBinding() {
        this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
        this.Url = "http://localhost:8081/Analytics_V1_05/RuleEnginePortImpl";
    }
    
    /// <remarks/>
    public event GetSupportedRulesCompletedEventHandler GetSupportedRulesCompleted;
    
    /// <remarks/>
    public event CreateRulesCompletedEventHandler CreateRulesCompleted;
    
    /// <remarks/>
    public event DeleteRulesCompletedEventHandler DeleteRulesCompleted;
    
    /// <remarks/>
    public event GetRulesCompletedEventHandler GetRulesCompleted;
    
    /// <remarks/>
    public event ModifyRulesCompletedEventHandler ModifyRulesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/GetSupportedRules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("SupportedRules")]
    public SupportedRules GetSupportedRules(string ConfigurationToken) {
        object[] results = this.Invoke("GetSupportedRules", new object[] {
                    ConfigurationToken});
        return ((SupportedRules)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetSupportedRules(string ConfigurationToken, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetSupportedRules", new object[] {
                    ConfigurationToken}, callback, asyncState);
    }
    
    /// <remarks/>
    public SupportedRules EndGetSupportedRules(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SupportedRules)(results[0]));
    }
    
    /// <remarks/>
    public void GetSupportedRulesAsync(string ConfigurationToken) {
        this.GetSupportedRulesAsync(ConfigurationToken, null);
    }
    
    /// <remarks/>
    public void GetSupportedRulesAsync(string ConfigurationToken, object userState) {
        if ((this.GetSupportedRulesOperationCompleted == null)) {
            this.GetSupportedRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSupportedRulesOperationCompleted);
        }
        this.InvokeAsync("GetSupportedRules", new object[] {
                    ConfigurationToken}, this.GetSupportedRulesOperationCompleted, userState);
    }
    
    private void OnGetSupportedRulesOperationCompleted(object arg) {
        if ((this.GetSupportedRulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetSupportedRulesCompleted(this, new GetSupportedRulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/CreateRules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void CreateRules(string ConfigurationToken, [System.Xml.Serialization.XmlElementAttribute("Rule")] Config[] Rule) {
        this.Invoke("CreateRules", new object[] {
                    ConfigurationToken,
                    Rule});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateRules(string ConfigurationToken, Config[] Rule, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateRules", new object[] {
                    ConfigurationToken,
                    Rule}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndCreateRules(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void CreateRulesAsync(string ConfigurationToken, Config[] Rule) {
        this.CreateRulesAsync(ConfigurationToken, Rule, null);
    }
    
    /// <remarks/>
    public void CreateRulesAsync(string ConfigurationToken, Config[] Rule, object userState) {
        if ((this.CreateRulesOperationCompleted == null)) {
            this.CreateRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRulesOperationCompleted);
        }
        this.InvokeAsync("CreateRules", new object[] {
                    ConfigurationToken,
                    Rule}, this.CreateRulesOperationCompleted, userState);
    }
    
    private void OnCreateRulesOperationCompleted(object arg) {
        if ((this.CreateRulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateRulesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/DeleteRules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DeleteRules(string ConfigurationToken, [System.Xml.Serialization.XmlElementAttribute("RuleName")] string[] RuleName) {
        this.Invoke("DeleteRules", new object[] {
                    ConfigurationToken,
                    RuleName});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteRules(string ConfigurationToken, string[] RuleName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteRules", new object[] {
                    ConfigurationToken,
                    RuleName}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndDeleteRules(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void DeleteRulesAsync(string ConfigurationToken, string[] RuleName) {
        this.DeleteRulesAsync(ConfigurationToken, RuleName, null);
    }
    
    /// <remarks/>
    public void DeleteRulesAsync(string ConfigurationToken, string[] RuleName, object userState) {
        if ((this.DeleteRulesOperationCompleted == null)) {
            this.DeleteRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRulesOperationCompleted);
        }
        this.InvokeAsync("DeleteRules", new object[] {
                    ConfigurationToken,
                    RuleName}, this.DeleteRulesOperationCompleted, userState);
    }
    
    private void OnDeleteRulesOperationCompleted(object arg) {
        if ((this.DeleteRulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteRulesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/GetRules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("Rule")]
    public Config[] GetRules(string ConfigurationToken) {
        object[] results = this.Invoke("GetRules", new object[] {
                    ConfigurationToken});
        return ((Config[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetRules(string ConfigurationToken, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetRules", new object[] {
                    ConfigurationToken}, callback, asyncState);
    }
    
    /// <remarks/>
    public Config[] EndGetRules(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Config[])(results[0]));
    }
    
    /// <remarks/>
    public void GetRulesAsync(string ConfigurationToken) {
        this.GetRulesAsync(ConfigurationToken, null);
    }
    
    /// <remarks/>
    public void GetRulesAsync(string ConfigurationToken, object userState) {
        if ((this.GetRulesOperationCompleted == null)) {
            this.GetRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRulesOperationCompleted);
        }
        this.InvokeAsync("GetRules", new object[] {
                    ConfigurationToken}, this.GetRulesOperationCompleted, userState);
    }
    
    private void OnGetRulesOperationCompleted(object arg) {
        if ((this.GetRulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetRulesCompleted(this, new GetRulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/ModifyRules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void ModifyRules(string ConfigurationToken, [System.Xml.Serialization.XmlElementAttribute("Rule")] Config[] Rule) {
        this.Invoke("ModifyRules", new object[] {
                    ConfigurationToken,
                    Rule});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginModifyRules(string ConfigurationToken, Config[] Rule, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ModifyRules", new object[] {
                    ConfigurationToken,
                    Rule}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndModifyRules(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void ModifyRulesAsync(string ConfigurationToken, Config[] Rule) {
        this.ModifyRulesAsync(ConfigurationToken, Rule, null);
    }
    
    /// <remarks/>
    public void ModifyRulesAsync(string ConfigurationToken, Config[] Rule, object userState) {
        if ((this.ModifyRulesOperationCompleted == null)) {
            this.ModifyRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyRulesOperationCompleted);
        }
        this.InvokeAsync("ModifyRules", new object[] {
                    ConfigurationToken,
                    Rule}, this.ModifyRulesOperationCompleted, userState);
    }
    
    private void OnModifyRulesOperationCompleted(object arg) {
        if ((this.ModifyRulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ModifyRulesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="AnalyticsEngineBinding", Namespace="http://www.onvif.org/ver20/analytics/wsdl")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageDescription))]
public partial class AnalyticsEngineBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetServiceCapabilitiesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetSupportedAnalyticsModulesOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateAnalyticsModulesOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteAnalyticsModulesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAnalyticsModulesOperationCompleted;
    
    private System.Threading.SendOrPostCallback ModifyAnalyticsModulesOperationCompleted;
    
    /// <remarks/>
    public AnalyticsEngineBinding() {
        this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
        this.Url = "http://localhost:8081/Analytics_V1_05/AnalyticsEnginePortImpl";
    }
    
    /// <remarks/>
    public event GetServiceCapabilitiesCompletedEventHandler GetServiceCapabilitiesCompleted;
    
    /// <remarks/>
    public event GetSupportedAnalyticsModulesCompletedEventHandler GetSupportedAnalyticsModulesCompleted;
    
    /// <remarks/>
    public event CreateAnalyticsModulesCompletedEventHandler CreateAnalyticsModulesCompleted;
    
    /// <remarks/>
    public event DeleteAnalyticsModulesCompletedEventHandler DeleteAnalyticsModulesCompleted;
    
    /// <remarks/>
    public event GetAnalyticsModulesCompletedEventHandler GetAnalyticsModulesCompleted;
    
    /// <remarks/>
    public event ModifyAnalyticsModulesCompletedEventHandler ModifyAnalyticsModulesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/GetServiceCapabilities", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("Capabilities")]
    public Capabilities GetServiceCapabilities() {
        object[] results = this.Invoke("GetServiceCapabilities", new object[0]);
        return ((Capabilities)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetServiceCapabilities(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetServiceCapabilities", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public Capabilities EndGetServiceCapabilities(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Capabilities)(results[0]));
    }
    
    /// <remarks/>
    public void GetServiceCapabilitiesAsync() {
        this.GetServiceCapabilitiesAsync(null);
    }
    
    /// <remarks/>
    public void GetServiceCapabilitiesAsync(object userState) {
        if ((this.GetServiceCapabilitiesOperationCompleted == null)) {
            this.GetServiceCapabilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceCapabilitiesOperationCompleted);
        }
        this.InvokeAsync("GetServiceCapabilities", new object[0], this.GetServiceCapabilitiesOperationCompleted, userState);
    }
    
    private void OnGetServiceCapabilitiesOperationCompleted(object arg) {
        if ((this.GetServiceCapabilitiesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetServiceCapabilitiesCompleted(this, new GetServiceCapabilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/GetSupportedAnalyticsModules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("SupportedAnalyticsModules")]
    public SupportedAnalyticsModules GetSupportedAnalyticsModules(string ConfigurationToken) {
        object[] results = this.Invoke("GetSupportedAnalyticsModules", new object[] {
                    ConfigurationToken});
        return ((SupportedAnalyticsModules)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetSupportedAnalyticsModules(string ConfigurationToken, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetSupportedAnalyticsModules", new object[] {
                    ConfigurationToken}, callback, asyncState);
    }
    
    /// <remarks/>
    public SupportedAnalyticsModules EndGetSupportedAnalyticsModules(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SupportedAnalyticsModules)(results[0]));
    }
    
    /// <remarks/>
    public void GetSupportedAnalyticsModulesAsync(string ConfigurationToken) {
        this.GetSupportedAnalyticsModulesAsync(ConfigurationToken, null);
    }
    
    /// <remarks/>
    public void GetSupportedAnalyticsModulesAsync(string ConfigurationToken, object userState) {
        if ((this.GetSupportedAnalyticsModulesOperationCompleted == null)) {
            this.GetSupportedAnalyticsModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSupportedAnalyticsModulesOperationCompleted);
        }
        this.InvokeAsync("GetSupportedAnalyticsModules", new object[] {
                    ConfigurationToken}, this.GetSupportedAnalyticsModulesOperationCompleted, userState);
    }
    
    private void OnGetSupportedAnalyticsModulesOperationCompleted(object arg) {
        if ((this.GetSupportedAnalyticsModulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetSupportedAnalyticsModulesCompleted(this, new GetSupportedAnalyticsModulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/CreateAnalyticsModules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void CreateAnalyticsModules(string ConfigurationToken, [System.Xml.Serialization.XmlElementAttribute("AnalyticsModule")] Config[] AnalyticsModule) {
        this.Invoke("CreateAnalyticsModules", new object[] {
                    ConfigurationToken,
                    AnalyticsModule});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateAnalyticsModules(string ConfigurationToken, Config[] AnalyticsModule, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateAnalyticsModules", new object[] {
                    ConfigurationToken,
                    AnalyticsModule}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndCreateAnalyticsModules(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void CreateAnalyticsModulesAsync(string ConfigurationToken, Config[] AnalyticsModule) {
        this.CreateAnalyticsModulesAsync(ConfigurationToken, AnalyticsModule, null);
    }
    
    /// <remarks/>
    public void CreateAnalyticsModulesAsync(string ConfigurationToken, Config[] AnalyticsModule, object userState) {
        if ((this.CreateAnalyticsModulesOperationCompleted == null)) {
            this.CreateAnalyticsModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAnalyticsModulesOperationCompleted);
        }
        this.InvokeAsync("CreateAnalyticsModules", new object[] {
                    ConfigurationToken,
                    AnalyticsModule}, this.CreateAnalyticsModulesOperationCompleted, userState);
    }
    
    private void OnCreateAnalyticsModulesOperationCompleted(object arg) {
        if ((this.CreateAnalyticsModulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateAnalyticsModulesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/DeleteAnalyticsModules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DeleteAnalyticsModules(string ConfigurationToken, [System.Xml.Serialization.XmlElementAttribute("AnalyticsModuleName")] string[] AnalyticsModuleName) {
        this.Invoke("DeleteAnalyticsModules", new object[] {
                    ConfigurationToken,
                    AnalyticsModuleName});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteAnalyticsModules(string ConfigurationToken, string[] AnalyticsModuleName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteAnalyticsModules", new object[] {
                    ConfigurationToken,
                    AnalyticsModuleName}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndDeleteAnalyticsModules(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void DeleteAnalyticsModulesAsync(string ConfigurationToken, string[] AnalyticsModuleName) {
        this.DeleteAnalyticsModulesAsync(ConfigurationToken, AnalyticsModuleName, null);
    }
    
    /// <remarks/>
    public void DeleteAnalyticsModulesAsync(string ConfigurationToken, string[] AnalyticsModuleName, object userState) {
        if ((this.DeleteAnalyticsModulesOperationCompleted == null)) {
            this.DeleteAnalyticsModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAnalyticsModulesOperationCompleted);
        }
        this.InvokeAsync("DeleteAnalyticsModules", new object[] {
                    ConfigurationToken,
                    AnalyticsModuleName}, this.DeleteAnalyticsModulesOperationCompleted, userState);
    }
    
    private void OnDeleteAnalyticsModulesOperationCompleted(object arg) {
        if ((this.DeleteAnalyticsModulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteAnalyticsModulesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/GetAnalyticsModules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("AnalyticsModule")]
    public Config[] GetAnalyticsModules(string ConfigurationToken) {
        object[] results = this.Invoke("GetAnalyticsModules", new object[] {
                    ConfigurationToken});
        return ((Config[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAnalyticsModules(string ConfigurationToken, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAnalyticsModules", new object[] {
                    ConfigurationToken}, callback, asyncState);
    }
    
    /// <remarks/>
    public Config[] EndGetAnalyticsModules(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Config[])(results[0]));
    }
    
    /// <remarks/>
    public void GetAnalyticsModulesAsync(string ConfigurationToken) {
        this.GetAnalyticsModulesAsync(ConfigurationToken, null);
    }
    
    /// <remarks/>
    public void GetAnalyticsModulesAsync(string ConfigurationToken, object userState) {
        if ((this.GetAnalyticsModulesOperationCompleted == null)) {
            this.GetAnalyticsModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAnalyticsModulesOperationCompleted);
        }
        this.InvokeAsync("GetAnalyticsModules", new object[] {
                    ConfigurationToken}, this.GetAnalyticsModulesOperationCompleted, userState);
    }
    
    private void OnGetAnalyticsModulesOperationCompleted(object arg) {
        if ((this.GetAnalyticsModulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAnalyticsModulesCompleted(this, new GetAnalyticsModulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver20/analytics/wsdl/ModifyAnalyticsModules", RequestNamespace="http://www.onvif.org/ver20/analytics/wsdl", ResponseNamespace="http://www.onvif.org/ver20/analytics/wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void ModifyAnalyticsModules(string ConfigurationToken, [System.Xml.Serialization.XmlElementAttribute("AnalyticsModule")] Config[] AnalyticsModule) {
        this.Invoke("ModifyAnalyticsModules", new object[] {
                    ConfigurationToken,
                    AnalyticsModule});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginModifyAnalyticsModules(string ConfigurationToken, Config[] AnalyticsModule, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ModifyAnalyticsModules", new object[] {
                    ConfigurationToken,
                    AnalyticsModule}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndModifyAnalyticsModules(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void ModifyAnalyticsModulesAsync(string ConfigurationToken, Config[] AnalyticsModule) {
        this.ModifyAnalyticsModulesAsync(ConfigurationToken, AnalyticsModule, null);
    }
    
    /// <remarks/>
    public void ModifyAnalyticsModulesAsync(string ConfigurationToken, Config[] AnalyticsModule, object userState) {
        if ((this.ModifyAnalyticsModulesOperationCompleted == null)) {
            this.ModifyAnalyticsModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyAnalyticsModulesOperationCompleted);
        }
        this.InvokeAsync("ModifyAnalyticsModules", new object[] {
                    ConfigurationToken,
                    AnalyticsModule}, this.ModifyAnalyticsModulesOperationCompleted, userState);
    }
    
    private void OnModifyAnalyticsModulesOperationCompleted(object arg) {
        if ((this.ModifyAnalyticsModulesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ModifyAnalyticsModulesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class SupportedRules {
    
    private string[] ruleContentSchemaLocationField;
    
    private ConfigDescription[] ruleDescriptionField;
    
    private SupportedRulesExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RuleContentSchemaLocation", DataType="anyURI")]
    public string[] RuleContentSchemaLocation {
        get {
            return this.ruleContentSchemaLocationField;
        }
        set {
            this.ruleContentSchemaLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RuleDescription")]
    public ConfigDescription[] RuleDescription {
        get {
            return this.ruleDescriptionField;
        }
        set {
            this.ruleDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public SupportedRulesExtension Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ConfigDescription {
    
    private ItemListDescription parametersField;
    
    private ConfigDescriptionMessages[] messagesField;
    
    private ConfigDescriptionExtension extensionField;
    
    private System.Xml.XmlQualifiedName nameField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public ItemListDescription Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Messages")]
    public ConfigDescriptionMessages[] Messages {
        get {
            return this.messagesField;
        }
        set {
            this.messagesField = value;
        }
    }
    
    /// <remarks/>
    public ConfigDescriptionExtension Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescription {
    
    private ItemListDescriptionSimpleItemDescription[] simpleItemDescriptionField;
    
    private ItemListDescriptionElementItemDescription[] elementItemDescriptionField;
    
    private ItemListDescriptionExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SimpleItemDescription")]
    public ItemListDescriptionSimpleItemDescription[] SimpleItemDescription {
        get {
            return this.simpleItemDescriptionField;
        }
        set {
            this.simpleItemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElementItemDescription")]
    public ItemListDescriptionElementItemDescription[] ElementItemDescription {
        get {
            return this.elementItemDescriptionField;
        }
        set {
            this.elementItemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public ItemListDescriptionExtension Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescriptionSimpleItemDescription {
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class SupportedAnalyticsModulesExtension {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class SupportedAnalyticsModules {
    
    private string[] analyticsModuleContentSchemaLocationField;
    
    private ConfigDescription[] analyticsModuleDescriptionField;
    
    private SupportedAnalyticsModulesExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnalyticsModuleContentSchemaLocation", DataType="anyURI")]
    public string[] AnalyticsModuleContentSchemaLocation {
        get {
            return this.analyticsModuleContentSchemaLocationField;
        }
        set {
            this.analyticsModuleContentSchemaLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnalyticsModuleDescription")]
    public ConfigDescription[] AnalyticsModuleDescription {
        get {
            return this.analyticsModuleDescriptionField;
        }
        set {
            this.analyticsModuleDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public SupportedAnalyticsModulesExtension Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl")]
public partial class Capabilities {
    
    private System.Xml.XmlElement[] anyField;
    
    private bool ruleSupportField;
    
    private bool ruleSupportFieldSpecified;
    
    private bool analyticsModuleSupportField;
    
    private bool analyticsModuleSupportFieldSpecified;
    
    private bool cellBasedSceneDescriptionSupportedField;
    
    private bool cellBasedSceneDescriptionSupportedFieldSpecified;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RuleSupport {
        get {
            return this.ruleSupportField;
        }
        set {
            this.ruleSupportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RuleSupportSpecified {
        get {
            return this.ruleSupportFieldSpecified;
        }
        set {
            this.ruleSupportFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool AnalyticsModuleSupport {
        get {
            return this.analyticsModuleSupportField;
        }
        set {
            this.analyticsModuleSupportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AnalyticsModuleSupportSpecified {
        get {
            return this.analyticsModuleSupportFieldSpecified;
        }
        set {
            this.analyticsModuleSupportFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool CellBasedSceneDescriptionSupported {
        get {
            return this.cellBasedSceneDescriptionSupportedField;
        }
        set {
            this.cellBasedSceneDescriptionSupportedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CellBasedSceneDescriptionSupportedSpecified {
        get {
            return this.cellBasedSceneDescriptionSupportedFieldSpecified;
        }
        set {
            this.cellBasedSceneDescriptionSupportedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListExtension {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemList {
    
    private ItemListSimpleItem[] simpleItemField;
    
    private ItemListElementItem[] elementItemField;
    
    private ItemListExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SimpleItem")]
    public ItemListSimpleItem[] SimpleItem {
        get {
            return this.simpleItemField;
        }
        set {
            this.simpleItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElementItem")]
    public ItemListElementItem[] ElementItem {
        get {
            return this.elementItemField;
        }
        set {
            this.elementItemField = value;
        }
    }
    
    /// <remarks/>
    public ItemListExtension Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListSimpleItem {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListElementItem {
    
    private System.Xml.XmlElement anyField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class Config {
    
    private ItemList parametersField;
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    /// <remarks/>
    public ItemList Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class SupportedRulesExtension {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ConfigDescriptionExtension {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class MessageDescriptionExtension {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class MessageDescription {
    
    private ItemListDescription sourceField;
    
    private ItemListDescription keyField;
    
    private ItemListDescription dataField;
    
    private MessageDescriptionExtension extensionField;
    
    private bool isPropertyField;
    
    private bool isPropertyFieldSpecified;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public ItemListDescription Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public ItemListDescription Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public ItemListDescription Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public MessageDescriptionExtension Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsProperty {
        get {
            return this.isPropertyField;
        }
        set {
            this.isPropertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPropertySpecified {
        get {
            return this.isPropertyFieldSpecified;
        }
        set {
            this.isPropertyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescriptionExtension {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescriptionElementItemDescription {
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ConfigDescriptionMessages : MessageDescription {
    
    private string parentTopicField;
    
    /// <remarks/>
    public string ParentTopic {
        get {
            return this.parentTopicField;
        }
        set {
            this.parentTopicField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetSupportedRulesCompletedEventHandler(object sender, GetSupportedRulesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetSupportedRulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetSupportedRulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SupportedRules Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SupportedRules)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void CreateRulesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void DeleteRulesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetRulesCompletedEventHandler(object sender, GetRulesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetRulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetRulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Config[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Config[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ModifyRulesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetServiceCapabilitiesCompletedEventHandler(object sender, GetServiceCapabilitiesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetServiceCapabilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetServiceCapabilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Capabilities Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Capabilities)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetSupportedAnalyticsModulesCompletedEventHandler(object sender, GetSupportedAnalyticsModulesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetSupportedAnalyticsModulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetSupportedAnalyticsModulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SupportedAnalyticsModules Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SupportedAnalyticsModules)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void CreateAnalyticsModulesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void DeleteAnalyticsModulesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetAnalyticsModulesCompletedEventHandler(object sender, GetAnalyticsModulesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAnalyticsModulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAnalyticsModulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Config[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Config[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ModifyAnalyticsModulesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
