//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.IntegrationService.LoginStatusServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginStatusServiceRef.ILoginStatus")]
    public interface ILoginStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginStatus/CheckStatus", ReplyAction="http://tempuri.org/ILoginStatus/CheckStatusResponse")]
        int CheckStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginStatus/CheckStatus", ReplyAction="http://tempuri.org/ILoginStatus/CheckStatusResponse")]
        System.Threading.Tasks.Task<int> CheckStatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginStatusChannel : AMS.Broker.IntegrationService.LoginStatusServiceRef.ILoginStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginStatusClient : System.ServiceModel.ClientBase<AMS.Broker.IntegrationService.LoginStatusServiceRef.ILoginStatus>, AMS.Broker.IntegrationService.LoginStatusServiceRef.ILoginStatus {
        
        public LoginStatusClient() {
        }
        
        public LoginStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckStatus() {
            return base.Channel.CheckStatus();
        }
        
        public System.Threading.Tasks.Task<int> CheckStatusAsync() {
            return base.Channel.CheckStatusAsync();
        }
    }
}
