//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/03/26 - 14:18:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract, KnownType(typeof(ContactDto)), KnownType(typeof(AccountInvoiceDto)), 
    KnownType(typeof(AddressDto)), KnownType(typeof(DeliveryMethodDto)), KnownType(typeof(ServicePackageDto)),
    KnownType(typeof(AccountTypeDto)), KnownType(typeof(AccountBillingDto)), KnownType(typeof(AccountAlarmPanelDto)),
    KnownType(typeof(AccountAnalyticsAlgorithmTypeDto)), KnownType(typeof(AccountNvrAlertTypeDto))]
    public partial class AccountDto
    {
        [DataMember()]
        public Int32 AccountId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String AccountNumber { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String Location { get; set; }

        [DataMember()]
        public String WebSiteURL { get; set; }

        [DataMember()]
        public Nullable<Int32> TimeZoneId { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreatedOn { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModifiedOn { get; set; }

        [DataMember()]
        public Nullable<Int32> ModifiedBy { get; set; }

        [DataMember()]
        public Nullable<Int32> AccountTypeId { get; set; }

        [DataMember()]
        public Nullable<Int32> ParentAccountId { get; set; }

        public AccountDto ParentAccount { get; set; }

        [DataMember()]
        public Nullable<Int32> ServicePackageId { get; set; }

        [DataMember()]
        public Int32 DeletionStateCode { get; set; }

        [DataMember()]
        public Nullable<Int32> PrimaryContactId { get; set; }

        [DataMember()]
        public List<AccountDto> ChildAccounts { get; set; }

        [DataMember()]
        public List<AddressDto> Address { get; set; }

        [DataMember()]
        public List<AccountInvoiceDto> AccountInvoice { get; set; }

        [DataMember()]
        public ContactDto Contact { get; set; }

        [DataMember()]
        public List<ContactDto> Contacts { get; set; }

        [DataMember()]
        public string Email { get; set; }

        [DataMember()]
        public int? AccountBillingId { get; set; }

        [DataMember()]
        public AccountBillingDto AccountBilling { get; set; }

        [DataMember()]
        public PersonDto PrimaryAccountAdministrator { get; set; }

        [DataMember()]
        public byte[] AccountLogo { get; set; }

        [DataMember()]
        public IList<AccountAlarmPanelDto> AccountAlarmPanel { get; set; }

        [DataMember()]
        public IList<AccountAnalyticsAlgorithmTypeDto> AccountAnalyticsAlgorithmType { get; set; }

        [DataMember()]
        public IList<AccountNvrAlertTypeDto> AccountNvrAlertType { get; set; }

        [DataMember()]
        public Nullable<int> Sites { get; set; }

        [DataMember()]
        public Nullable<int> Devices { get; set; }

        [DataMember()]
        public bool BillingSameAsAccountAddress { get; set; }

        [DataMember()]
        public Nullable<int> UserCount { get; set; }
        
        public AccountDto()
        {
        }
    }
}
