//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/03/26 - 14:18:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class DeliveryMethodDto
    {
        [DataMember()]
        public Int32 DeliveryMethodId { get; set; }

        [DataMember()]
        public String DeliveryMethodName { get; set; }

        [DataMember()]
        public Int32 Frequency { get; set; }

        [DataMember()]
        public List<AccountDto> Account { get; set; }

        [DataMember()]
        public List<AccountTypeDto> AccountType { get; set; }

        public FrequencyDto Frequency1 { get; set; }

        public DeliveryMethodDto()
        {
        }
    }
}
