//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/08/01 - 09:05:04
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class DeviceExternalIdDefinitionDto
    {
        [DataMember()]
        public EventFieldDefinitionDto EventFieldDefinition { get; set; }

        [DataMember()]
        public Int32 order { get; set; }

        [DataMember()]
        public Int32 InterfaceId { get; set; }
    }
}
