//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/05/24 - 14:59:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract, KnownType(typeof(EventGroupDto))]
    public partial class EventCodeDto
    {
        [DataMember]
        public Int32 EventCode { get; set; }

        [DataMember]
        public String EventAssociated { get; set; }

        [DataMember]
        public int EventGroupId { get; set; }

        [DataMember]
        public EventGroupDto EventGroup { get; set; }
    }
}
