//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/03/26 - 14:18:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class ServicePackageDto
    {
        [DataMember()]
        public Int32 ServicePackageId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Decimal PackagePrice { get; set; }

        /*[DataMember()]
        public List<AccountDto> Account { get; set; }*/

        public ServicePackageDto()
        {
        }
    }
}
