//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/04/14 - 21:09:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblDisasterManagementDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Organization { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public String FacilityType { get; set; }

        [DataMember()]
        public String PostalCode { get; set; }

        [DataMember()]
        public String TotalBeds { get; set; }

        [DataMember()]
        public String AvailableBeds { get; set; }

        [DataMember()]
        public String Role { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public String EmailID { get; set; }

        [DataMember()]
        public String VehicleNo { get; set; }

        [DataMember()]
        public String VehicleType { get; set; }

        [DataMember()]
        public String Location { get; set; }

        [DataMember()]
        public String ShelterType { get; set; }

        [DataMember()]
        public String Latitude { get; set; }

        [DataMember()]
        public String Longitude { get; set; }

        [DataMember()]
        public String EntityFlag { get; set; }

        [DataMember()]
        public String AlertFlag { get; set; }

        public tblDisasterManagementDTO()
        {
        }

        public tblDisasterManagementDTO(Int32 iD, String name, String organization, String address, String facilityType, String postalCode, String totalBeds, String availableBeds, String role, String mobileNo, String emailID, String vehicleNo, String vehicleType, String location, String shelterType, String latitude, String longitude, String entityFlag, String alertFlag)
        {
			this.ID = iD;
			this.Name = name;
			this.Organization = organization;
			this.Address = address;
			this.FacilityType = facilityType;
			this.PostalCode = postalCode;
			this.TotalBeds = totalBeds;
			this.AvailableBeds = availableBeds;
			this.Role = role;
			this.MobileNo = mobileNo;
			this.EmailID = emailID;
			this.VehicleNo = vehicleNo;
			this.VehicleType = vehicleType;
			this.Location = location;
			this.ShelterType = shelterType;
			this.Latitude = latitude;
			this.Longitude = longitude;
			this.EntityFlag = entityFlag;
			this.AlertFlag = alertFlag;
        }
    }
}
