//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/08/06 - 16:33:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblgeofencesequenceDTO
    {
        [DataMember()]
        public Int32 SeqID { get; set; }

        [DataMember()]
        public Int32 DeviceID { get; set; }

        [DataMember()]
        public Int32 SiteID { get; set; }

        [DataMember()]
        public Nullable<Int32> SeqNo { get; set; }

        public tblgeofencesequenceDTO()
        {
        }

        public tblgeofencesequenceDTO(Int32 seqID, Int32 deviceID, Int32 siteID, Nullable<Int32> seqNo)
        {
			this.SeqID = seqID;
			this.DeviceID = deviceID;
			this.SiteID = siteID;
			this.SeqNo = seqNo;
        }
    }
}
