//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/05/27 - 15:51:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblWeatherchastronomyDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> AstronomyDate { get; set; }

        [DataMember()]
        public String CityName { get; set; }

        [DataMember()]
        public Nullable<Int32> CityID { get; set; }

        [DataMember()]
        public Nullable<DateTime> Sunrise { get; set; }

        [DataMember()]
        public Nullable<DateTime> Sunset { get; set; }

        public tblWeatherchastronomyDTO()
        {
        }

        public tblWeatherchastronomyDTO(Int32 iD, Nullable<DateTime> astronomyDate, String cityName, Nullable<Int32> cityID, Nullable<DateTime> sunrise, Nullable<DateTime> sunset)
        {
            this.ID = iD;
            this.AstronomyDate = astronomyDate;
            this.CityName = cityName;
            this.CityID = cityID;
            this.Sunrise = sunrise;
            this.Sunset = sunset;
        }
    }
}
