//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeonMembers
    {
        public int ID { get; set; }
        public string IMEI_Number { get; set; }
        public string Mobile_Number { get; set; }
        public string CustomerID { get; set; }
    }
}
