//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/09/09 - 12:32:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class AlarmPanelDTO:InterfaceDto
    {
        [DataMember()]
        public Nullable<Int32> EventTypeTemplateId { get; set; }

         [DataMember()]
        public int AlarmPanelId { get; set; }

        [DataMember()]
        public Nullable<Int32> AlarmPanelTypeId { get; set; }

        [DataMember()]
        public String InterfaceDeviceIP { get; set; }

        [DataMember()]
        public String InterfaceDevicePort { get; set; }

        public AlarmPanelDTO()
        {
        }

        public AlarmPanelDTO(Nullable<Int32> eventTypeTemplateId, Nullable<Int32> alarmPanelTypeId, String interfaceDeviceIP, String interfaceDevicePort, int alarmPanelId)
        {
			this.EventTypeTemplateId = eventTypeTemplateId;
			this.AlarmPanelTypeId = alarmPanelTypeId;
			this.InterfaceDeviceIP = interfaceDeviceIP;
			this.InterfaceDevicePort = interfaceDevicePort;
            this.AlarmPanelId = alarmPanelId;
        }
    }
}
