//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/09/09 - 12:29:43
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class AlarmPanelTypeMasterDTO
    {
        [DataMember()]
        public Int32 AlarmPanelTypeId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Description { get; set; }

        public AlarmPanelTypeMasterDTO()
        {
        }

        public AlarmPanelTypeMasterDTO(Int32 alarmPanelTypeId, String name, String description)
        {
			this.AlarmPanelTypeId = alarmPanelTypeId;
			this.Name = name;
			this.Description = description;
        }
    }
}
