//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/05/27 - 14:35:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class EventFieldDefinitionDto
    {
        [DataMember()]
        public Int32 EventFieldId { get; set; }

        [DataMember()]
        public String FieldName { get; set; }

        [DataMember()]
        public Int32 StartByte { get; set; }

        [DataMember()]
        public Int32 NumberOfBytes { get; set; }

        [DataMember()]
        public EventTypeTemplateDto EventTypeTemplate { get; set; }

        [DataMember()]
        public int EventTypeTemplateId { get; set; }

        [DataMember()]
        public EventFieldTypeDto EventFieldType { get; set; }
    }
}
