//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/06/19 - 19:00:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_GetSiteCollection_ResultDTO
    {
        [DataMember()]
        public Int32 SiteId { get; set; }

        [DataMember()]
        public Nullable<Int32> AccountId { get; set; }

        [DataMember()]
        public Double Alt { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String siteTypeName { get; set; }

        [DataMember()]
        public Double Long_ { get; set; }

        [DataMember()]
        public Double Lat { get; set; }

        [DataMember()]
        public Nullable<Double> ZoomLevel { get; set; }

        [DataMember()]
        public String PinUrl { get; set; }

        [DataMember()]
        public Nullable<Int32> ParentId { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsBingMap { get; set; }

        [DataMember()]
        public String Country { get; set; }

        [DataMember()]
        public String County { get; set; }

        [DataMember()]
        public String City { get; set; }

        [DataMember()]
        public String Line1 { get; set; }

        [DataMember()]
        public String Line2 { get; set; }

        [DataMember()]
        public String PostalCode { get; set; }

        [DataMember()]
        public Nullable<Int64> DeviceId { get; set; }

        [DataMember()]
        public String Name1 { get; set; }

        [DataMember()]
        public Nullable<Double> Lat1 { get; set; }

        [DataMember()]
        public Nullable<Double> Long1 { get; set; }

        [DataMember()]
        public Nullable<Double> Altitude { get; set; }

        [DataMember()]
        public String Type { get; set; }

        [DataMember()]
        public Nullable<Int32> SiteId1 { get; set; }

        [DataMember()]
        public Nullable<Double> Alt1 { get; set; }

        [DataMember()]
        public Nullable<Int32> BBoxPointId { get; set; }

        [DataMember()]
        public Nullable<Double> Lat2 { get; set; }

        [DataMember()]
        public Nullable<Double> Long2 { get; set; }

        [DataMember()]
        public Nullable<Int32> SiteId2 { get; set; }

        public SP_GetSiteCollection_ResultDTO()
        {
        }

        public SP_GetSiteCollection_ResultDTO(Int32 siteId, Nullable<Int32> accountId, Double alt, String description, String name, String siteTypeName, Double long_, Double lat, Nullable<Double> zoomLevel, String pinUrl, Nullable<Int32> parentId, Nullable<Boolean> isBingMap, String country, String county, String city, String line1, String line2, String postalCode, Nullable<Int64> deviceId, String name1, Nullable<Double> lat1, Nullable<Double> long1, Nullable<Double> altitude, String type, Nullable<Int32> siteId1, Nullable<Double> alt1, Nullable<Int32> bBoxPointId, Nullable<Double> lat2, Nullable<Double> long2, Nullable<Int32> siteId2)
        {
			this.SiteId = siteId;
			this.AccountId = accountId;
			this.Alt = alt;
			this.Description = description;
			this.Name = name;
			this.siteTypeName = siteTypeName;
			this.Long_ = long_;
			this.Lat = lat;
			this.ZoomLevel = zoomLevel;
			this.PinUrl = pinUrl;
			this.ParentId = parentId;
			this.IsBingMap = isBingMap;
			this.Country = country;
			this.County = county;
			this.City = city;
			this.Line1 = line1;
			this.Line2 = line2;
			this.PostalCode = postalCode;
			this.DeviceId = deviceId;
			this.Name1 = name1;
			this.Lat1 = lat1;
			this.Long1 = long1;
			this.Altitude = altitude;
			this.Type = type;
			this.SiteId1 = siteId1;
			this.Alt1 = alt1;
			this.BBoxPointId = bBoxPointId;
			this.Lat2 = lat2;
			this.Long2 = long2;
			this.SiteId2 = siteId2;
        }
    }
}
