//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/06/19 - 18:55:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_GetContactCollection_ResultDTO
    {
        [DataMember()]
        public Int32 ContactId { get; set; }

        [DataMember()]
        public Nullable<Guid> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreatedOn { get; set; }

        [DataMember()]
        public String EmailAddress { get; set; }

        [DataMember()]
        public String FaxNumber { get; set; }

        [DataMember()]
        public String LyncName { get; set; }

        [DataMember()]
        public String MobileNumber { get; set; }

        [DataMember()]
        public Nullable<Guid> ModifiedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModifiedOn { get; set; }

        [DataMember()]
        public Nullable<Int32> PersonId { get; set; }

        [DataMember()]
        public Int32 ContactId1 { get; set; }

        [DataMember()]
        public Int32 ContactMethodId { get; set; }

        [DataMember()]
        public Int32 PreferedContacMethodtId { get; set; }

        public SP_GetContactCollection_ResultDTO()
        {
        }

        public SP_GetContactCollection_ResultDTO(Int32 contactId, Nullable<Guid> createdBy, Nullable<DateTime> createdOn, String emailAddress, String faxNumber, String lyncName, String mobileNumber, Nullable<Guid> modifiedBy, Nullable<DateTime> modifiedOn, Nullable<Int32> personId, Int32 contactId1, Int32 contactMethodId, Int32 preferedContacMethodtId)
        {
			this.ContactId = contactId;
			this.CreatedBy = createdBy;
			this.CreatedOn = createdOn;
			this.EmailAddress = emailAddress;
			this.FaxNumber = faxNumber;
			this.LyncName = lyncName;
			this.MobileNumber = mobileNumber;
			this.ModifiedBy = modifiedBy;
			this.ModifiedOn = modifiedOn;
			this.PersonId = personId;
			this.ContactId1 = contactId1;
			this.ContactMethodId = contactMethodId;
			this.PreferedContacMethodtId = preferedContacMethodtId;
        }
    }
}
