//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/24 - 21:14:48
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_ReturnRuleDefinition_ResultDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Nullable<Int32> AlertDevice { get; set; }

        [DataMember()]
        public Nullable<Int32> DeviceID { get; set; }

        [DataMember()]
        public String Severity { get; set; }

        [DataMember()]
        public Nullable<Int32> EventyType { get; set; }

        [DataMember()]
        public Nullable<Int32> TimeSec { get; set; }

        [DataMember()]
        public Nullable<DateTime> FromTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> ToTime { get; set; }

        [DataMember()]
        public bool IsAlertflag { get; set; }

        public SP_ReturnRuleDefinition_ResultDTO()
        {
        }

        public SP_ReturnRuleDefinition_ResultDTO(Int32 iD, Nullable<Int32> alertDevice, Nullable<Int32> deviceID, String severity, Nullable<Int32> eventyType, Nullable<Int32> timeSec, Nullable<DateTime> fromTime, Nullable<DateTime> toTime, bool isAlertflag)
        {
			this.ID = iD;
			this.AlertDevice = alertDevice;
			this.DeviceID = deviceID;
			this.Severity = severity;
			this.EventyType = eventyType;
			this.TimeSec = timeSec;
			this.FromTime = fromTime;
			this.ToTime = toTime;
            this.IsAlertflag = IsAlertflag;
        }
    }
}
