//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/02/21 - 19:16:04
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_ReturnUserName_ResultDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String UserName { get; set; }

        [DataMember()]
        public String UserID { get; set; }

        public SP_ReturnUserName_ResultDTO()
        {
        }

        public SP_ReturnUserName_ResultDTO(Int32 iD, String userName, String UserID)
        {
            this.ID = iD;
            this.UserName = userName;
            this.UserID = UserID;
        }
    }
}
