//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/02/16 - 12:39:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_ReturnActiveStationIP_ResultDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String StationIP { get; set; }

        [DataMember()]
        public string Authtoken { get; set; }
        
        [DataMember()]
        public string Identifier { get; set; }

        public SP_ReturnActiveStationIP_ResultDTO()
        {
        }

        public SP_ReturnActiveStationIP_ResultDTO(Int32 iD, String stationIP, String authtoken, String identifier)
        {
			this.ID = iD;
			this.StationIP = stationIP;
            this.Authtoken = authtoken;
            this.Identifier = identifier;
        }
    }
}
