//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/04/29 - 10:20:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class SP_ReturnMosaicStation_ResultDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Nullable<Int32> StationID { get; set; }

        [DataMember()]
        public String StationType { get; set; }

        public SP_ReturnMosaicStation_ResultDTO()
        {
        }

        public SP_ReturnMosaicStation_ResultDTO(Int32 iD, Nullable<Int32> stationID, String stationType)
        {
			this.ID = iD;
			this.StationID = stationID;
            this.StationType = stationType;
        }
    }
}
