//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/11/29 - 18:46:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblcustomeremergencycontactDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Int32 SiteID { get; set; }

        [DataMember()]
        public String Title { get; set; }

        [DataMember()]
        public String contactname { get; set; }

        [DataMember()]
        public String contactno { get; set; }

        [DataMember()]
        public String contactemailid { get; set; }

        [DataMember()]
        public String contactrelation { get; set; }

        [DataMember()]
        public String ownershipinfo { get; set; }

        [DataMember()]
        public Nullable<Boolean> deletionflag { get; set; }

        [DataMember]
        public string firstname { get; set; }

        [DataMember]
        public string lastname { get; set; }

        [DataMember]
        public string apartmentname { get; set; }

        [DataMember]
        public string flag { get; set; }

        [DataMember()]
        public Int32 LevelID { get; set; }

        public tblcustomeremergencycontactDTO()
        {
        }

        public tblcustomeremergencycontactDTO(Int32 iD, Int32 siteID, String title, String contactname, String contactno, String contactemailid, String contactrelation, String ownershipinfo, Nullable<Boolean> deletionflag,Int32 levelID)
        {
            this.ID = iD;
            this.SiteID = siteID;
            this.Title = title;
            this.contactname = contactname;
            this.contactno = contactno;
            this.contactemailid = contactemailid;
            this.contactrelation = contactrelation;
            this.ownershipinfo = ownershipinfo;
            this.deletionflag = deletionflag;
            this.firstname = firstname;
            this.lastname = lastname;
            this.apartmentname = apartmentname;
            this.flag = flag;
            this.LevelID = levelID;
        }
    }
}
