//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/03/28 - 16:00:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblCustomMapinfoDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Int32 SiteID { get; set; }

        [DataMember()]
        public String SiteName { get; set; }

        [DataMember()]
        public Byte[] Map { get; set; }

        [DataMember()]
        public Boolean IsBingMap { get; set; }

        public tblCustomMapinfoDTO()
        {
        }

        public tblCustomMapinfoDTO(Int32 iD, Int32 siteID, String siteName, Byte[] map, Boolean isBingMap)
        {
			this.ID = iD;
			this.SiteID = siteID;
			this.SiteName = siteName;
			this.Map = map;
			this.IsBingMap = isBingMap;
        }
    }
}
