//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/21 - 11:30:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblDeviceGeoTrackHistoryDTO
    {
        [DataMember()]
        public Int64 DevMovHisID { get; set; }

        [DataMember()]
        public Int64 DevId { get; set; }

        [DataMember()]
        public String AssetName { get; set; }

        [DataMember()]
        public Double LATITUDE { get; set; }

        [DataMember()]
        public Double LONGITUDE { get; set; }

        [DataMember()]
        public String SPEED { get; set; }

        [DataMember()]
        public String HEADING { get; set; }

        [DataMember()]
        public Nullable<DateTime> POSDATETIME { get; set; }

        [DataMember()]
        public Nullable<Int32> IGNSTATUS { get; set; }

        [DataMember()]
        public String LOCATION { get; set; }

        public tblDeviceGeoTrackHistoryDTO()
        {
        }

        public tblDeviceGeoTrackHistoryDTO(Int64 devMovHisID, Int64 devId, String assetName, Double lATITUDE, Double lONGITUDE, String sPEED, String hEADING, Nullable<DateTime> pOSDATETIME, Nullable<Int32> iGNSTATUS, String lOCATION)
        {
            this.DevMovHisID = devMovHisID;
            this.DevId = devId;
            this.AssetName = assetName;
            this.LATITUDE = lATITUDE;
            this.LONGITUDE = lONGITUDE;
            this.SPEED = sPEED;
            this.HEADING = hEADING;
            this.POSDATETIME = pOSDATETIME;
            this.IGNSTATUS = iGNSTATUS;
            this.LOCATION = lOCATION;
        }
    }
}
