//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/24 - 20:14:18
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblEventsDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String RawData { get; set; }

        [DataMember()]
        public String Client_no { get; set; }

        [DataMember()]
        public Nullable<Int32> Type_No { get; set; }

        [DataMember()]
        public Nullable<Int32> Zone { get; set; }

        [DataMember()]
        public Nullable<DateTime> EventDateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> ReceivedDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> TransactionID { get; set; }

        [DataMember()]
        public String BranchID { get; set; }

         [DataMember()]
        public Nullable<Int32> AlertID { get; set; }
        
        
        public tblEventsDTO()
        {
        }

        public tblEventsDTO(Int32 iD, Nullable<Int32> transactionID, String rawData, String client_no, Nullable<Int32> type_No, Nullable<Int32> zone, Nullable<DateTime> eventDateTime, Nullable<DateTime> receivedDateTime, String branchID, Nullable<Int32> alertID)
        {
			this.ID = iD;
			this.RawData = rawData;
			this.Client_no = client_no;
			this.Type_No = type_No;
			this.Zone = zone;
			this.EventDateTime = eventDateTime;
			this.ReceivedDateTime = receivedDateTime;
            this.TransactionID = transactionID;
            this.BranchID = branchID;
            this.AlertID = alertID;
        }
    }
}
