//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2018/01/12 - 20:42:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblEnvironmentSensorDataDTO
    {
        [DataMember()]
        public Int64 ID { get; set; }

        [DataMember()]
        public String PayLod_M2m_G3 { get; set; }

        [DataMember()]
        public String PayLod_M2m_G2 { get; set; }

        [DataMember()]
        public String PayLod_M2m_G5 { get; set; }

        [DataMember()]
        public String PayLod_M2m_G8 { get; set; }

        [DataMember()]
        public String PayLod_M2m_G7 { get; set; }

        [DataMember()]
        public String PayLod_M2m_Hum { get; set; }

        [DataMember()]
        public String PayLod_M2m_Lat { get; set; }

        [DataMember()]
        public String PayLod_M2m_Lon { get; set; }

        [DataMember()]
        public String PayLod_M2m_P1 { get; set; }

        [DataMember()]
        public String PayLod_M2m_P2 { get; set; }

        [DataMember()]
        public String PayLod_M2m_T { get; set; }

        [DataMember()]
        public String PayLod_M2m_Temp { get; set; }

        [DataMember()]
        public String PayLod_M2m_wd { get; set; }

        [DataMember()]
        public String PayLod_M2m_Ws { get; set; }

        [DataMember()]
        public String Topic { get; set; }

        [DataMember()]
        public String UniqueId { get; set; }

        [DataMember()]
        public String UniqueIdType { get; set; }

        [DataMember()]
        public Nullable<DateTime> ReceiveDateTime { get; set; }

        [DataMember()]
        public Nullable<Int64> AlertID { get; set; }

        [DataMember()]
        public Nullable<Int64> DeviceID { get; set; }

        public tblEnvironmentSensorDataDTO()
        {
        }

        public tblEnvironmentSensorDataDTO(Int64 iD, String payLod_M2m_G3, String payLod_M2m_G2, String payLod_M2m_G5, String payLod_M2m_G7, String payLod_M2m_G8, String payLod_M2m_Hum, String payLod_M2m_Lat, String payLod_M2m_Lon, String payLod_M2m_P1, String payLod_M2m_P2, String payLod_M2m_T, String payLod_M2m_Temp, String payLod_M2m_wd, String payLod_M2m_Ws, String topic, String uniqueId, String uniqueIdType, Nullable<DateTime> receiveDateTime, Nullable<Int64> alertID, Nullable<Int64> deviceID)
        {
            this.ID = iD;
            this.PayLod_M2m_G3 = payLod_M2m_G3;
            this.PayLod_M2m_G2 = payLod_M2m_G2;
            this.PayLod_M2m_G5 = payLod_M2m_G5;
            this.PayLod_M2m_G8 = payLod_M2m_G8;
            this.PayLod_M2m_G7 = payLod_M2m_G7;
            this.PayLod_M2m_Hum = payLod_M2m_Hum;
            this.PayLod_M2m_Lat = payLod_M2m_Lat;
            this.PayLod_M2m_Lon = payLod_M2m_Lon;
            this.PayLod_M2m_P1 = payLod_M2m_P1;
            this.PayLod_M2m_P2 = payLod_M2m_P2;
            this.PayLod_M2m_T = payLod_M2m_T;
            this.PayLod_M2m_Temp = payLod_M2m_Temp;
            this.PayLod_M2m_wd = payLod_M2m_wd;
            this.PayLod_M2m_Ws = payLod_M2m_Ws;
            this.Topic = topic;
            this.UniqueId = uniqueId;
            this.UniqueIdType = uniqueIdType;
            this.ReceiveDateTime = receiveDateTime;
            this.AlertID = alertID;
            this.DeviceID = deviceID;
        }
    }
}
