//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/08/27 - 10:26:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblRssFeedDto
    {
        [DataMember()]
        public Int32 RSSID { get; set; }

        [DataMember()]
        public String RssText { get; set; }

        [DataMember()]
        public Nullable<DateTime> RssPublisdateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> RssLastUpdateTime { get; set; }

        public tblRssFeedDto()
        {
        }

        public tblRssFeedDto(Int32 rSSID, String rssText, Nullable<DateTime> rssPublisdateTime, Nullable<DateTime> rssLastUpdateTime)
        {
			this.RSSID = rSSID;
			this.RssText = rssText;
			this.RssPublisdateTime = rssPublisdateTime;
			this.RssLastUpdateTime = rssLastUpdateTime;
        }
    }
}
