//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/10/11 - 20:14:13
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblSMTPConfigurationDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String SMTPServer { get; set; } 

        [DataMember()]
        public String SMTPPort { get; set; }

        [DataMember()]
        public String SMTPUser { get; set; }

        [DataMember()]
        public String SMTPPassword { get; set; }

        [DataMember()]
        public Nullable<Boolean> UseAuthentication { get; set; }

        [DataMember()]
        public Nullable<Boolean> UseSSL { get; set; }

        [DataMember()]
        public String FromAddress { get; set; }

        [DataMember()]
        public String EmailDisplayName { get; set; }

        [DataMember()]
        public string Name { get; set; }


        public tblSMTPConfigurationDTO()
        {
        }

        public tblSMTPConfigurationDTO(Int32 iD, String sMTPServer, String sMTPPort, String sMTPUser, String sMTPPassword, Nullable<Boolean> useAuthentication, Nullable<Boolean> useSSL, String fromAddress, String emailDisplayName, string name)
        {
			this.ID = iD;
			this.SMTPServer = sMTPServer;
			this.SMTPPort = sMTPPort;
			this.SMTPUser = sMTPUser;
			this.SMTPPassword = sMTPPassword;
			this.UseAuthentication = useAuthentication;
			this.UseSSL = useSSL;
			this.FromAddress = fromAddress;
			this.EmailDisplayName = emailDisplayName;
            this.Name = name;
        }
    }
}
