//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/03/07 - 16:11:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblSOPTypeDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String SOPType { get; set; }

        public tblSOPTypeDTO()
        {
        }

        public tblSOPTypeDTO(Int32 iD, String sOPType)
        {
			this.ID = iD;
			this.SOPType = sOPType;
        }
    }
}
