//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/08/24 - 10:50:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblSiteHolidayListDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public Nullable<Int32> SiteID { get; set; }

        [DataMember()]
        public Nullable<Int32> HolidayMasterID { get; set; }

        public tblSiteHolidayListDTO()
        {
        }
        public tblSiteHolidayListDTO(Int32 iD, Nullable<Int32> siteID, Nullable<Int32> holidayMasterID)
        {
			this.ID = iD;
			this.SiteID = siteID;
			this.HolidayMasterID = holidayMasterID;
        }
    }
}
