//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/05/27 - 15:52:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace AMS.Broker.Contracts.DTO
{
    [DataContract()]
    public partial class tblWeatherchforecastDTO
    {
        [DataMember()]
        public Int32 ID { get; set; }

        [DataMember()]
        public String CityName { get; set; }

        [DataMember()]
        public Nullable<Int32> CityID { get; set; }

        [DataMember()]
        public Nullable<Int32> TransactionID { get; set; }

        [DataMember()]
        public Nullable<DateTime> ForecastDate { get; set; }

        [DataMember()]
        public Nullable<Int32> ForecastPeriod { get; set; }

        [DataMember()]
        public String ForeCastDay { get; set; }

        [DataMember()]
        public String ForecastIcon { get; set; }

        [DataMember()]
        public String ForecastIconurl { get; set; }

        [DataMember()]
        public String Daytitle { get; set; }

        [DataMember()]
        public String ForecastText { get; set; }

        [DataMember()]
        public Nullable<Int32> POP { get; set; }

        [DataMember()]
        public Nullable<Int32> AlertID { get; set; }

        public tblWeatherchforecastDTO()
        {
        }

        public tblWeatherchforecastDTO(Int32 iD, String cityName, Nullable<Int32> cityID, Nullable<Int32> transactionID, Nullable<DateTime> forecastDate, Nullable<Int32> forecastPeriod, String foreCastDay, String forecastIcon, String forecastIconurl, String daytitle, String forecastText, Nullable<Int32> pOP, Nullable<Int32> alertID)
        {
            this.ID = iD;
            this.CityName = cityName;
            this.CityID = cityID;
            this.TransactionID = transactionID;
            this.ForecastDate = forecastDate;
            this.ForecastPeriod = forecastPeriod;
            this.ForeCastDay = foreCastDay;
            this.ForecastIcon = forecastIcon;
            this.ForecastIconurl = forecastIconurl;
            this.Daytitle = daytitle;
            this.ForecastText = forecastText;
            this.POP = pOP;
            this.AlertID = alertID;
        }
    }
}
