//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvrCamera : Device
    {
        public Nullable<int> FPS { get; set; }
        public int AnalyticAlgorithmTypeId { get; set; }
        public string Version { get; set; }
        public Nullable<int> MaxBlobSize { get; set; }
        public Nullable<int> MinBlobSize { get; set; }
        public Nullable<int> AlarmDelay { get; set; }
        public Nullable<decimal> UpdateRate { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> ZoneRows { get; set; }
        public Nullable<int> ZoneColumns { get; set; }
        public byte[] ZoneData { get; set; }
        public Nullable<int> AnalyticsEventTemplateId { get; set; }
        public Nullable<bool> IsPtz { get; set; }
        public string CameraIp { get; set; }
        public string LineStart { get; set; }
        public string LineEnd { get; set; }
        public Nullable<int> DirectionFlag { get; set; }
        public string CameraUrl { get; set; }
        public string CameraPort { get; set; }
        public string CamUser { get; set; }
        public string CamPassword { get; set; }
        public Nullable<int> MaxBlobWidth { get; set; }
        public Nullable<int> MaxBlobHeight { get; set; }
        public Nullable<int> MinBlobWidth { get; set; }
        public Nullable<int> MinBlobHeight { get; set; }
        public Nullable<int> CameraType { get; set; }
        public string AnalyticsServerIp { get; set; }
        public Nullable<int> Lane1 { get; set; }
        public Nullable<int> Lane2 { get; set; }
        public Nullable<int> Lane3 { get; set; }
        public Nullable<int> NoOfLens { get; set; }
        public Nullable<int> ChanelNo { get; set; }
        public Nullable<int> IsEdgeAnalytics { get; set; }
    
        public virtual AnalyticAlgorithmType AnalyticAlgorithmType { get; set; }
        public virtual AnalyticsEventTemplate AnalyticsEventTemplate { get; set; }
    }
}
