//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRssFeed
    {
        public int RSSID { get; set; }
        public string RssText { get; set; }
        public Nullable<System.DateTime> RssPublisdateTime { get; set; }
        public Nullable<System.DateTime> RssLastUpdateTime { get; set; }
    }
}
