//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class NVR
    {
        public NVR()
        {
            this.Device = new HashSet<Device>();
        }
    
        public long NvrId { get; set; }
        public string NvrUrl { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Port { get; set; }
        public string Description { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> InterfaceId { get; set; }
        public Nullable<int> DvrNvrTypeId { get; set; }
        public Nullable<int> CameraStream { get; set; }
    
        public virtual ICollection<Device> Device { get; set; }
        public virtual DvrNvrTypeMaster DvrNvrTypeMaster { get; set; }
        public virtual Interface Interface { get; set; }
    }
}
