//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlertEscalationLog
    {
        public int ID { get; set; }
        public Nullable<int> AlertID { get; set; }
        public string IdentifierIP { get; set; }
        public Nullable<bool> EscalationStatus { get; set; }
        public Nullable<System.DateTime> EscalationDatetime { get; set; }
    }
}
