//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnvironmentSensorData
    {
        public long ID { get; set; }
        public string PayLod_M2m_G3 { get; set; }
        public string PayLod_M2m_G2 { get; set; }
        public string PayLod_M2m_G5 { get; set; }
        public string PayLod_M2m_G8 { get; set; }
        public string PayLod_M2m_Hum { get; set; }
        public string PayLod_M2m_Lat { get; set; }
        public string PayLod_M2m_Lon { get; set; }
        public string PayLod_M2m_P1 { get; set; }
        public string PayLod_M2m_P2 { get; set; }
        public string PayLod_M2m_T { get; set; }
        public string PayLod_M2m_Temp { get; set; }
        public string PayLod_M2m_wd { get; set; }
        public string PayLod_M2m_Ws { get; set; }
        public string Topic { get; set; }
        public string UniqueId { get; set; }
        public string UniqueIdType { get; set; }
        public Nullable<System.DateTime> ReceiveDateTime { get; set; }
        public Nullable<long> AlertID { get; set; }
        public Nullable<long> DeviceID { get; set; }
        public string PayLod_M2m_G7 { get; set; }
        public Nullable<double> PayLod_M2m_bs { get; set; }
        public Nullable<double> PayLod_M2m_leq { get; set; }
        public Nullable<double> PayLod_M2m_lmin { get; set; }
        public Nullable<double> PayLod_M2m_lmax { get; set; }
        public Nullable<double> PayLod_M2m_rain { get; set; }
        public Nullable<double> PayLod_M2m_light { get; set; }
        public Nullable<double> PayLod_M2m_flood { get; set; }
        public Nullable<double> PayLod_M2m_AQI { get; set; }
    }
}
