//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnvironmentthreshold
    {
        public int ID { get; set; }
        public string SensorType { get; set; }
        public Nullable<decimal> ThresholdValue { get; set; }
        public string SensorID { get; set; }
    }
}
