//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHolidayMaster
    {
        public int ID { get; set; }
        public int StateID { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public string HolidayDescription { get; set; }
    }
}
