//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSOPType
    {
        public tblSOPType()
        {
            this.tblSOPMaster = new HashSet<tblSOPMaster>();
            this.tblSOPTriggerActionType = new HashSet<tblSOPTriggerActionType>();
        }
    
        public int ID { get; set; }
        public string SOPType { get; set; }
    
        public virtual ICollection<tblSOPMaster> tblSOPMaster { get; set; }
        public virtual ICollection<tblSOPTriggerActionType> tblSOPTriggerActionType { get; set; }
    }
}
