//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicleTrackingData
    {
        public long ID { get; set; }
        public string Latitude { get; set; }
        public string Location { get; set; }
        public string Longitude { get; set; }
        public string Speed { get; set; }
        public string Updated { get; set; }
        public string Veh_reg { get; set; }
        public Nullable<System.DateTime> ReceivedDateTime { get; set; }
        public string Resv1 { get; set; }
        public string Resv2 { get; set; }
        public string Resv3 { get; set; }
    }
}
