//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWasteBinSensorData
    {
        public long ID { get; set; }
        public string DeviceID { get; set; }
        public string Manufacturer { get; set; }
        public string ModelId { get; set; }
        public string MessageType { get; set; }
        public Nullable<int> Ac { get; set; }
        public Nullable<bool> AccOff { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Address { get; set; }
        public Nullable<int> Mmi_DeviceID { get; set; }
        public string DigitalInput1 { get; set; }
        public string DigitalInput3 { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string FuelLevel { get; set; }
        public Nullable<bool> GpsFix { get; set; }
        public string Gsmlevel { get; set; }
        public string Heading { get; set; }
        public string HeatSinkTemp { get; set; }
        public string Mmi_ID { get; set; }
        public Nullable<bool> IndianBox { get; set; }
        public Nullable<long> InsertTime { get; set; }
        public string Latitude { get; set; }
        public string LocationSource { get; set; }
        public string Longitude { get; set; }
        public string MovementStatus { get; set; }
        public string NumberOfSatellites { get; set; }
        public Nullable<bool> History { get; set; }
        public string Speed { get; set; }
        public string Timestamp { get; set; }
        public string UniqueId { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<bool> validGPS { get; set; }
        public Nullable<System.DateTime> ReceiveDateTime { get; set; }
        public Nullable<long> AlertID { get; set; }
        public Nullable<long> DevID { get; set; }
    }
}
