//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public Zone()
        {
            this.DevicesInZone = new HashSet<DevicesInZone>();
            this.ZoneGroup = new HashSet<ZoneGroup>();
            this.ZoneGroup1 = new HashSet<ZoneGroup>();
            this.ZoneLocation = new HashSet<ZoneLocation>();
            this.ZoneUser = new HashSet<ZoneUser>();
        }
    
        public long ZoneId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Metadata { get; set; }
    
        public virtual ICollection<DevicesInZone> DevicesInZone { get; set; }
        public virtual ICollection<ZoneGroup> ZoneGroup { get; set; }
        public virtual ICollection<ZoneGroup> ZoneGroup1 { get; set; }
        public virtual ICollection<ZoneLocation> ZoneLocation { get; set; }
        public virtual ICollection<ZoneUser> ZoneUser { get; set; }
    }
}
