//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Broker.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Account = new HashSet<Account>();
            this.PreferedContatMethod = new HashSet<PreferedContatMethod>();
        }
    
        public int ContactId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string TelephoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string LyncName { get; set; }
        public string FaxNumber { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<PreferedContatMethod> PreferedContatMethod { get; set; }
    }
}
